### PR TITLE
Update nightwatch and chromedriver, adjust other items as necessary t…

### PR DESCRIPTION
**Pull request by CBonade**
…o accommodate the changes and reduce dependency on selenium

## Description

The goal of this PR was to upgrade Nightwatch and Chromedriver to their newest versions, as well as any alterations to the environment and tests needed in conjunction with that.  This is modeled after the steps that were taken on vets-website.

## Testing done
Tested in CLI locally and all tests pass.  All checks pass when pushing to Github as well.

## Screenshots
image

## Acceptance criteria
- [ ]

## Definition of done
- [ ] Events are logged appropriately
- [ ] Documentation has been updated, if applicable
- [ ] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)
- [ ] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

### CODE REVIEW

**Review by U-DON — APPROVED** [review]

**Comment by ddzz** [comment]
Looks good. We need to test this with the daily a11y scan before we merge. cc @timwright12

**Review by 1Copenut — APPROVED** [review]
LGTM! @ddzz beat me to the comment about testing with the daily a11y scan before merging.

**Comment by timwright12** [comment]
Can we hold off on this one until we turn off Jenkins daily a11y scan? Just want to get a clean metric to we can close that out

**Comment by CBonade** [comment]
Closing this as Nightwatch is getting ready to be removed from content-build

**Pull request closed without merging**
