### PR TITLE
VACMS 19273 - menu exception manila and add to menus download

### PR DESCRIPTION
**Pull request by eselkin**
## Summary

- Adds manila-va-clinic to menu download, but because manila-va-clinic has no parent, exception is created to allow menus to be created for it.
- Sitewide team (we own facility pages)

## Related issue(s)

- https://github.com/department-of-veterans-affairs/va.gov-cms/issues/19273

## Testing done

- Manual testing by numerous people for existence of menus, breadcrumbs accessibility, and get updates box correctness

## Screenshots

<details>
<summary>Manila VAMC main page</summary>
Screenshot 2024-10-07 at 1 28 21 PM
</details>

<details>
<summary>Manila VAMC main page - showing breadcrumb to current page content</summary>
Screenshot 2024-10-07 at 1 28 47 PM
</details>

<details>
<summary>Manila VAMC main page - showing link to About us nested page</summary>
Screenshot 2024-10-07 at 1 29 05 PM
</details>

<details>
<summary>Manila VAMC About Us page - with breadcrumb back to Manila VAMC (not system) </summary>
Screenshot 2024-10-07 at 1 29 26 PM

</details>

<details>
<summary>Manila VAMC main page - Get Updates content</summary>
Screenshot 2024-10-07 at 1 31 16 PM
</details>

## What areas of the site does it impact?

Manila VAMC page

## Acceptance criteria

- [x] Manila menu appears on the left sidenav of Manila VA Clinic pages based on Section
- [x] Preview works on Manila pages
- [x] Manila pages build successfully

### Quality Assurance & Testing

- [x] I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [x] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs
- [x] Linting warnings have been addressed
- [x] Documentation has been updated ([link to documentation](#) \*if necessary)
- [x] Screenshot of the developed feature is added
- [x] [Accessibility testing](https://depo-platform-documentation.scrollhelp.site/developer-docs/wcag-2-1-success-criteria-and-foundational-testing) has been performed

### Error Handling

- [x] Browser console contains no warnings or errors.
- [x] Events are being sent to the appropriate logging solution
- [x] Feature/bug has a monitor built into Datadog or Grafana (if applicable)

### Authentication

- [x] Did you login to a local build and verify all authenticated routes work as expected with a test user

## Requested Feedback

Because of the status of tugboats rebuilding every night and resetting, you'll have to test locally from a tugboat with Manila VAMC (not the system) published, and the Manila About Us page published and make sure the parent in the menu is pointing to the `About Manila VAMC` `<nolink>` menu section.

**To publish VAMC**
Go to: 
`/node/1059/edit`
Changes `Save as` to `published` and add some text in textbox and click save

**To publish About us page and make sure it's in the correct location go to**
`/manila-va-clinic/about-us`
then `edit`
then under `menu settings` on the right, choose:
`Parent link` to be: 
Screenshot 2024-10-07 at 10 19 38 PM
and keep the Alias URL the same.
Change save as to: `published`
add some text in the text box and `save`

Point your content build to the tugboat to build with:
`yarn build --use-cached-assets --pull-drupal --drupal-address=https://tugboatmainaddress`
and wait the 900000000 minutes

### CODE REVIEW

**Comment by randimays** [comment]
@eselkin Working on setting up a Tugboat to test.

> you'll have to test locally from a tugboat with Manila VAMC (not the system) published

Does this mean I need to publish the Manila VAMC (VAMC Facility)?

Screenshot 2024-10-08 at 10 41 59 AM

**Comment by eselkin** [comment]
Yes. Publish the facility. Not the VAMC System with the same name.

**Comment by jilladams** [comment]
(To match what will happen in Prod, the System should be Published > Archived)

**Comment by randimays** [comment]
@jilladams 
> (To match what will happen in Prod, the System should be Published > Archived)

Does this mean the VAMC System should be published, then archived?

**Comment by randimays** [comment]
@eselkin I don't have the option to select the correct menu in the About page per your instructions:
Screenshot 2024-10-08 at 3 00 34 PM



Screenshot 2024-10-08 at 2 58 56 PM

**Comment by jilladams** [comment]
@randimays yes: in Prod we are going to Publish and then Archive the Manila VAMC System. It would be best to do that for testing, to make sure that no behavior is negatively impacted by that change, when it happens.

**Comment by eselkin** [comment]
@randimays Sorry, didn't see the message. So, you can make a `<nolink>` menu item under Manila VA Clinic or spin up a new tugboat and that should have the right menu structure.

To make a nolink menu item, 
go to: 
`/admin/structure/menu/manage/manila-va-clinic`
Click "+ Add link" button at the top
In the title box add something like: `About Manila VA Clinic`
In the link box add: `<nolink>`
Make sure Enabled is still checked
In the Parent link section on the right Select
Screenshot 2024-10-08 at 4 12 30 PM
Then go back into the about us page and change the parent link to whatever you called the new nolink menu item under -- Manila VA Clinic

**Comment by eselkin** [comment]
So the Manila VA System page needs to be published -> archived once only. It's just so that it gets picked up for the Blue box about social links for the VAMC facility page.

**Comment by randimays** [comment]
@eselkin Should the VAMC system be published first, then the code tested, then it should be archived? Or published, then archived, then test the code?

**Comment by laflannery** [comment]
Tested tugboat matched screenshots and confirmed accessibility of Main page and About page - everything looks good!

**Review by randimays — APPROVED** [review]
LGTM

**Pull request merged**
