### PR TITLE
VACMS-15967: Fix search bar spacing in Common Tasks Section

### PR DESCRIPTION
**Pull request by chriskim2311**
## Summary
Change the margin property to a larger screen size media query so there is enough left hand space for the search bar at certain screen widths

## Related issue(s)

- _Link to ticket created in va.gov-team repo_
department-of-veterans-affairs/va.gov-cms#15967

## Testing done
Tested across multiple screen lengths to check for common tasks section spacing issues.

## Screenshots
Screen width 1010px. 
VA_gov_Home___Veterans_Affairs

## What areas of the site does it impact?

Homepage

### CODE REVIEW

**Review by randimays — COMMENTED** [review]
We need some adjustments around ~768-923px wide, the Top pages section is still too close to the right edge of the screen

Screenshot 2023-12-04 at 1 54 06 PM

**Review by randimays — COMMENTED** [review]
Can we shrink the right padding on `Top pages` down to 16px? The links are wrapping just a bit too much.

Screenshot 2023-12-05 at 2 13 16 PM

**Comment by randimays** [comment]
Apologies, I should have worded that a bit more clearly; I was only referring to the padding on the right side of the page (for `Top pages`). I think we need the wider padding on the left side of `Top pages`. Did you get a consult with Jordan yet?

**Review by maxx1128 — COMMENTED** [review]
Should we have equal spacing on the left sides of both "Search" and "Top Pages" for when both sections are squished? This is the page at 865px wide, and the left side spacing being different for both is throwing me off.

Screen Shot 2023-12-06 at 11 12 44 AM

**Comment by chriskim2311** [comment]
@thejordanwood Hi! Can you take a look at this PR env and let me know what you think would be best case forward. Randi and Max have made good points. Let me know what you recommend and I can implement the changes.

http://39ffe3b77fc34ce9f5758fa9dd4c0d1e.review.vetsgov-internal/

**Comment by aklausmeier** [comment]
@chriskim2311 I agree with @thejordanwood's spacing suggestions on her 800px annotated mockup.

**Comment by chriskim2311** [comment]
@thejordanwood @randimays @aklausmeier  
New Screenshots at 800px. I have handled both the initial ask of the search bar touching at certain widths and added more space for the links in the top pages section. Let me know if you see any other necessary changes thanks!

Before:
VA_gov_Home___Veterans_Affairs


After:

VA_gov_Home___Veterans_Affairs

**Comment by randimays** [comment]
@chriskim2311 I think there are still some spacing issues to address per [Jordan's comment](https://github.com/department-of-veterans-affairs/content-build/pull/1818#issuecomment-1846235860).

Here are some screenshots at a width right above the 768px breakpoint. Notice the search bar is creeping outside of its intended margin. There also should be 32px of padding on either side of the blue/white split in the middle per Jordan's comment.

Screenshot 2023-12-11 at 10 39 35 AM
Screenshot 2023-12-11 at 10 39 30 AM

**Comment by thejordanwood** [comment]
@randimays @aklausmeier

@chriskim2311 and I met about this to talk through the spacing. It looks like the search bar has a minimum width, which prevents us from using 32px of spacing at smaller screen sizes. I'm fine with the smaller spacing between the Search and Top pages sections shown in Chris' recent screenshot. 

The original problem for this ticket has been solved and the search bar no longer touches the edge of the screen on the left side at certain screen widths. With that in mind, this is approved by me but I would like @aklausmeier's final approval on this before merging.

**Review by randimays — APPROVED** [review]
Code LGTM; when design gives the green light I think we're good to go!

**Comment by aklausmeier** [comment]
@thejordanwood @randimays @chriskim2311 This is approved on my end!

**Pull request merged**
