### PR TITLE
Vacms 15383 disable accesibility gh action

### PR DESCRIPTION
**Pull request by ariperez**
closes department-of-veterans-affairs/va.gov-cms#15383

### CODE REVIEW

**Comment by ariperez** [comment]
@ndouglas , I'm assuming this includes a11y-heading. Both a11y jobs have been failing for ~4 mos

**Comment by ndouglas** [comment]
That's my understanding, but it's worth pinging @laflannery

**Comment by laflannery** [comment]
Yes sorry for not being clear @ariperez - The heading job we intentional stopped/failed/whatever was happening with it awhile ago for reasons. But now we want both of them to not run and not ping the slack channel please!

**Review by ndouglas — APPROVED** [review]

**Review by CBonade — APPROVED** [review]
LGTM

**Pull request merged**
