### PR TITLE
15766 See more events links

### PR DESCRIPTION
**Pull request by randimays**
## Summary
Currently, on events listings, there is a single link at the bottom to "See more events" ([example here](https://www.va.gov/outreach-and-events/events/64652/)). We want to update it to show 1 or 2 links based on whether it is VAMC-specific, or part of the outreach and events calendar, and add an "Other VA events" header to that section.

### VAMC-specific event links
Screenshot 2024-06-14 at 10 32 17 AM

**Note:** The top link will only be present **IF** the editor has selected a specific VAMC for this dropdown
Screenshot 2024-06-14 at 9 20 50 AM

### Not-VAMC-specific event links
Screenshot 2024-06-14 at 10 32 12 AM

## Related issue(s)
- https://github.com/department-of-veterans-affairs/va.gov-cms/issues/15766

## Testing done
Tested locally:
- /durham-health-care/events/69410/ (VAMC; should have 2 links)
- /dublin-health-care/events/69463/ (VAMC; should have 2 links)
- /alaska-health-care/events/65947/ (VAMC, but "Outreach and events" is selected for the calendar; should have 1 link)
- /western-new-york-health-care/events/69602/ (VAMC; should have 2 links)
- /outreach-and-events/events/69508/ (outreach; should have 1 link)
- /outreach-and-events/events/62367/ (outreach; should have 1 link)

### Tugboat testing
- https://web-f5nly9faca8qseksdpbxafx5f9nrb3z3.demo.cms.va.gov/durham-health-care/events/69410/
- https://web-f5nly9faca8qseksdpbxafx5f9nrb3z3.demo.cms.va.gov/dublin-health-care/events/69463/
- https://web-f5nly9faca8qseksdpbxafx5f9nrb3z3.demo.cms.va.gov/alaska-health-care/events/65947/
- https://web-f5nly9faca8qseksdpbxafx5f9nrb3z3.demo.cms.va.gov/western-new-york-health-care/events/69602/
- https://web-f5nly9faca8qseksdpbxafx5f9nrb3z3.demo.cms.va.gov/outreach-and-events/events/69508/
- https://web-f5nly9faca8qseksdpbxafx5f9nrb3z3.demo.cms.va.gov/outreach-and-events/events/62367/

## Screenshots

<details><summary>/durham-health-care/events/69410/ (VAMC)</summary>

### Desktop
Screenshot 2024-06-14 at 10 52 27 AM

### Mobile
Screenshot 2024-06-14 at 10 52 34 AM

</details>

<details><summary>/dublin-health-care/events/69463/ (VAMC)</summary>

### Desktop
Screenshot 2024-06-14 at 10 50 31 AM

### Mobile
Screenshot 2024-06-14 at 10 50 49 AM

</details>

<details><summary>/western-new-york-health-care/events/69602/ (VAMC)</summary>

### Desktop
Screenshot 2024-06-14 at 10 57 50 AM

### Mobile
Screenshot 2024-06-14 at 10 57 56 AM

</details>

<details><summary>/outreach-and-events/events/69508/ (outreach / national events)</summary>

### Desktop
Screenshot 2024-06-14 at 10 58 54 AM

### Mobile
Screenshot 2024-06-14 at 10 59 00 AM

</details>

<details><summary>/alaska-health-care/events/65947/ (VAMC with outreach & events selected)</summary>

### Desktop
Screenshot 2024-06-14 at 11 00 00 AM

### Mobile
Screenshot 2024-06-14 at 11 00 06 AM

</details>

### CODE REVIEW

**Comment by randimays** [comment]
@laflannery @thejordanwood Please review if you have a chance. The review instance never came up here, so I created a Tugboat (details in the description) for testing. Thanks!

**Comment by thejordanwood** [comment]
@randimays I had to look into this to refresh my memory. I think we landed on a different treatment than [#15766](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/15766) suggests. The [Outreach and Events Figma file](https://www.figma.com/design/SbGKt6EhjlHAvJOc9ENXow/Outreach-and-Events?node-id=40-1584&t=vfRPow5cEONXgU5k-1) shows that we should add a header and the links should be the default styling. 

**Timeline of how this evolved:**
- [#15766](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/15766) had a Mural board with IA suggestions. [This comment](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/15766#issuecomment-1834652552) on the ticket shows that new copy was going to be suggested. 
- [#16323](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/16323) is the ticket where new copy was suggested
- [#15946](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/15946) is the ticket where I did the design work and edited the copy a bit more. The Figma file is linked in that ticket as well. Amanda approved this, so it's probably the one we should go with.

**Comment by randimays** [comment]
@thejordanwood The Tugboat has been updated with the latest design / wording. Please review when you are able :) 

@chriskim2311 Could you re-review please?

**Comment by thejordanwood** [comment]
@randimays Thanks for updating that! I noticed on the VA Western NY page, the link was close to the header. The other pages looked fine though. 

This is what I see:
Screenshot 2024-06-12 at 4 59 24 PM

**Comment by randimays** [comment]
@thejordanwood Weird that it was only a problem on one of the VAMC events. In any case, it has been fixed and the Tugboat is updated!

**Comment by thejordanwood** [comment]
@randimays Thanks for fixing that. This looks good to me now!

**Comment by randimays** [comment]
> @randimays I found a weird one - I don't know if it's a content entry issue or what: https://web-f5nly9faca8qseksdpbxafx5f9nrb3z3.demo.cms.va.gov/outreach-and-events/events/62365/ Screenshot 2024-06-14 at 8 55 49 AM

Thank you @laflannery good find! This is a content entry issue. I went through the Drupal data returned to the FE for this page, and it doesn't have the VAMC anywhere for me to display. In the CMS they selected `Outreach and events` for the event. 

Screenshot 2024-06-14 at 9 20 50 AM

Is this a valid way to create a VAMC event? Should we plan for it and come up with a different way to handle this case? Or should we request that the editor change the selection? Given there are almost 9,000 events in the CMS, I'm sure this is selected on at least a few of them.

CC @dsasser

**Comment by randimays** [comment]
@laflannery This is ready for your review please

**Comment by jilladams** [comment]
That weird event is def one for follow up With VHA DM (which I'm gonna do in email now). We shouldn't be duping Events anymore.

**Review by laflannery — APPROVED** [review]
LGTM!

**Pull request merged**
