### PR TITLE
Log errors but do not halt on process.memoryUsage errors

### PR DESCRIPTION
**Pull request by eselkin**
## Summary

- Content-build fails due to process.memoryUsage errors because not handled gracefully
- Build PR 1912 on tugboat
- Surround process.memoryUsage calls with try/catch
- Sitewide Facilities

## Related issue(s)

- https://github.com/department-of-veterans-affairs/va.gov-cms/issues/18069

## Testing done

- Tested locally
- Tested on build that was failing on tugboat due to EMFILE errors

## Screenshots

N/A

Result of build with errors, but succeeding:

```
Step 44 end [7804ms]: Apply layouts Z

Step 45 of 54 start: Apply layouts 0-9.-_~!$&'()*+,;=:@
Error getting memBefore memory usage: Error: EMFILE: too many open files, uv_resident_set_memory
    at process.memoryUsage (internal/process/per_thread.js:153:5)
    at Timeout._onTimeout (/var/lib/tugboat/docroot/vendor/va-gov/content-build/src/site/stages/build/silversmith.js:182:31)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7) {
  errno: -24,
  code: 'EMFILE',
  syscall: 'uv_resident_set_memory'
}
Error getting memAfter memory usage: Error: EMFILE: too many open files, uv_resident_set_memory
    at process.memoryUsage (internal/process/per_thread.js:153:5)
    at Timeout._onTimeout (/var/lib/tugboat/docroot/vendor/va-gov/content-build/src/site/stages/build/silversmith.js:189:30)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7) {
  errno: -24,
  code: 'EMFILE',
  syscall: 'uv_resident_set_memory'
}
Step 45 end [130494ms]: Apply layouts 0-9.-_~!$&'()*+,;=:@
```

## What areas of the site does it impact?

silversmith build stage

## Acceptance criteria

Builds succeed

### Quality Assurance & Testing

- [ ] I fixed|updated|added unit tests and integration tests for each feature (N/A).
- [x] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs
- [x] Linting warnings have been addressed
- [x] Documentation has been updated (added comment in silversmith process)
- [ ] Screenshot of the developed feature is added (N/A)
- [ ] [Accessibility testing](https://depo-platform-documentation.scrollhelp.site/developer-docs/wcag-2-1-success-criteria-and-foundational-testing) has been performed (N/A)

### Error Handling

- [x] Browser console contains no warnings or errors.
- [x] Events are being sent to the appropriate logging solution
- [x] Feature/bug has a monitor built into Datadog or Grafana (if applicable)

### Authentication

- [ ] Did you login to a local build and verify all authenticated routes work as expected with a test user (N/A)

## Requested Feedback

Check that builds succeed on tugboat

### CODE REVIEW

**Comment by eselkin** [comment]
It's also possible that the tugboats need to increase the ulimit/open file limit to remove the error completely. As it stands the build process doesn't actually run out of memory on the tugboat (evidenced by the success of the build)

**Review by maxx1128 — APPROVED** [review]

**Comment by jilladams** [comment]
@gracekretschmer-metrostar @edmund-dunn @7hunderbird this PR must merge before we are able to launch service locations on Monday, in order to confirm our feature branch will be able to merge. Not a fire for today, technically, but will become one if not merged in time for Friday daily deploy for content-build. Apologies for fire drill.

**Comment by gracekretschmer-metrostar** [comment]
Thanks, @jilladams. Tyler is looking at it today.

**Review by 7hunderbird — COMMENTED** [review]
Hey Eli, just to double-check.  For https://github.com/department-of-veterans-affairs/content-build/pull/2070 do we need to include gracefulFs in the `metalsmith.js` file? or does it get inherited by the `index.js` in `src/site/stages/build` folder?

**Comment by eselkin** [comment]
It's inherited but doesn't change anything about the synchronous fs calls that memoryUsage makes, so it doesn't help us here.

**Review by 7hunderbird — APPROVED** [review]
Looks good to me.  Thanks!

**Review by 7hunderbird — APPROVED** [review]
adding the conditional stats output will be useful.  TY

**Comment by jilladams** [comment]
Thank you so much! You all are dealing with a lot, and we very very much appreciate the timely review!

**Pull request merged**
