### PR TITLE
VACMS 17511 fix use main facility phone 3rd time is the charm

### PR DESCRIPTION
**Pull request by eselkin**
THIS IS BRANCHED OFF Service Location Paragraph integration branch so tests will not pass

## Summary

- Makes main number conditional for appointments and contact info in Service Location Paragraphs and always shows optional numbers if they exist for both appointments and contact.
- Sitewide Facilities

## Related issue(s)

- https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17511

## Testing done

- tested locally and on Service Location integration site

## Screenshots

_Note: This field is mandatory for UI changes (non-component work should NOT have screenshots)._

<details>
<summary>Billing Service Location (new) with multiple contact numbers and Main Number checked</summary>
Screenshot 2024-04-04 at 3 30 13 PM
</details>

<details>
<summary>Clinical Service Location with appointment number and main number Off</summary>

Screenshot 2024-04-04 at 3 32 22 PM

Screenshot 2024-04-04 at 3 35 36 PM

</details>

## What areas of the site does it impact?

Updated Service Location Paragraph type only.

## Acceptance criteria

- [ ] Displays main number in appointments when "Use the facility phone number" is On.
- [ ] Displays alternate numbers in appointments when provided
- [ ] Displays main number in contact info when Use the general facility phone number is "Yes, display the general facility phone number"
- [ ] Displays alternate contact numbers

### Quality Assurance & Testing

- [x] I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [x] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs
- [x] Linting warnings have been addressed
- [x] Documentation has been updated ([link to documentation](#) \*if necessary)
- [x] Screenshot of the developed feature is added
- [ ] [Accessibility testing](https://depo-platform-documentation.scrollhelp.site/developer-docs/wcag-2-1-success-criteria-and-foundational-testing) has been performed

### Error Handling

- [x] Browser console contains no warnings or errors.
- [x] Events are being sent to the appropriate logging solution
- [x] Feature/bug has a monitor built into Datadog or Grafana (if applicable)

### Authentication

- [x] Did you login to a local build and verify all authenticated routes work as expected with a test user

## Requested Feedback

Check various clinical and non-clinical Service Locations on 
https://web-xptmfsnjoodldn85nzgkrgljqtfbz24b.ci.cms.va.gov/washington-dc-health-care/locations/washington-va-medical-center/
or 
https://web-xptmfsnjoodldn85nzgkrgljqtfbz24b.ci.cms.va.gov/washington-dc-health-care/billing-and-insurance/
or
https://web-xptmfsnjoodldn85nzgkrgljqtfbz24b.ci.cms.va.gov/northeast-ohio-health-care/billing-and-insurance/

### CODE REVIEW

**Comment by davidmpickett** [comment]
@maxx1128 Can you take a look at this PR when you have a chance so we can merge and close the ticket?

**Comment by jilladams** [comment]
(CI failures showing - kicked off a rerun.)

**Review by maxx1128 — APPROVED** [review]
👍

**Comment by eselkin** [comment]
CI will always show failures, it's on the integration branch

**Pull request merged**
