### PR TITLE
VACMS-10940 Consolidate reusable and page-specific Q&As on CLPs

### PR DESCRIPTION
**Pull request by randimays**
## Summary
None of our production Campaign Landing Pages use the Reusable Q&A feature **yet**, but when they do: we want the reusable Q&As that do not have a header to be combined under "Frequently Asked Questions." When the Reusable Q&A does have a header, we should see "Frequently Asked Questions" first with its accordions, and the header for the Reusable Q&As second with its accordions.

## Related issue(s)
- https://github.com/department-of-veterans-affairs/va.gov-cms/issues/10940

## Testing done
Tested locally at:

- /initiatives/protecting-veterans-from-fraud/
- /initiatives/veteran-trust-in-va/
- /initiatives/veterans-experience-action-centers/
- /initiatives/covid-flu/

## Screenshots

Note: some screenshots are back-to-back. Ignore any vertical spacing weirdness as it's probably just a "seam" between screenshots.

### Standard reusable Q&As with header

**URL**: https://web-fw8iwfgw7bk58wghnmcqhga5gprkrgrv.demo.cms.va.gov/initiatives/protecting-veterans-from-fraud

<details><summary>CMS data</summary>

Screenshot 2024-06-11 at 7 37 43 AM
Screenshot 2024-06-11 at 7 37 50 AM
</details>
<details><summary>Desktop view</summary>
Screenshot 2024-06-14 at 9 57 21 AM
Screenshot 2024-06-14 at 9 57 29 AM
Screenshot 2024-06-14 at 9 57 45 AM

</details>
<details><summary>Mobile view</summary>
Screenshot 2024-06-14 at 9 58 20 AM
Screenshot 2024-06-14 at 9 58 33 AM
Screenshot 2024-06-14 at 10 00 08 AM
Screenshot 2024-06-14 at 10 00 16 AM
Screenshot 2024-06-14 at 10 00 24 AM

</details>

### Standard reusable Q&As without header

**URL**: https://web-fw8iwfgw7bk58wghnmcqhga5gprkrgrv.demo.cms.va.gov/initiatives/veteran-trust-in-va/

<details><summary>CMS Data</summary>
Screenshot 2024-06-11 at 7 48 06 AM
Screenshot 2024-06-11 at 7 48 13 AM
</details>
<details><summary>Desktop view</summary>
Screenshot 2024-06-11 at 7 47 12 AM
Screenshot 2024-06-11 at 8 22 26 AM
Screenshot 2024-06-11 at 8 22 35 AM
Screenshot 2024-06-11 at 8 22 39 AM
</details>

<details><summary>Mobile view</summary>
Screenshot 2024-06-11 at 7 47 30 AM
Screenshot 2024-06-11 at 7 47 38 AM
Screenshot 2024-06-11 at 8 27 17 AM
Screenshot 2024-06-11 at 8 27 27 AM

Screenshot 2024-06-11 at 8 27 34 AM
Screenshot 2024-06-11 at 8 27 41 AM

</details>

### Accordion reusable Q&As with header

**URL**: https://web-fw8iwfgw7bk58wghnmcqhga5gprkrgrv.demo.cms.va.gov/initiatives/veterans-experience-action-centers/

<details><summary>CMS Data</summary>
Screenshot 2024-06-11 at 7 50 23 AM

Screenshot 2024-06-11 at 7 50 28 AM
</details>
<details><summary>Desktop view</summary>
Screenshot 2024-06-14 at 10 04 01 AM
Screenshot 2024-06-14 at 10 04 07 AM
Screenshot 2024-06-14 at 10 04 13 AM

</details>

<details><summary>Mobile view</summary>
Screenshot 2024-06-14 at 10 04 25 AM

Screenshot 2024-06-14 at 10 04 34 AM

Screenshot 2024-06-14 at 10 04 43 AM
Screenshot 2024-06-14 at 10 04 49 AM

</details>

### Accordion reusable Q&As without header

**URL**: https://web-fw8iwfgw7bk58wghnmcqhga5gprkrgrv.demo.cms.va.gov/initiatives/covid-flu/

<details><summary>CMS Data</summary>
Screenshot 2024-06-11 at 8 17 35 AM
Screenshot 2024-06-11 at 8 17 44 AM
</details>

<details><summary>Desktop view</summary>
Screenshot 2024-06-14 at 10 06 22 AM
Screenshot 2024-06-14 at 10 06 27 AM
Screenshot 2024-06-14 at 10 06 32 AM

</details>
<details><summary>Mobile view</summary>
Screenshot 2024-06-14 at 10 06 40 AM
Screenshot 2024-06-14 at 10 06 48 AM
Screenshot 2024-06-14 at 10 06 56 AM

Screenshot 2024-06-14 at 10 07 01 AM

</details>

### CODE REVIEW

**Review by chriskim2311 — APPROVED** [review]
LGTM tested in tugboat instances

**Comment by laflannery** [comment]
@randimays I am realizing we discussed the header but not the intro field and so it seems to be handled differently:
- In scenario 1 (Reusable header but the Q&As are not displaying as accordions) we are showing this in the middle
- In scenarios 3 + 4 (Reusable Q&As are showing as accordions) we aren't showing this at all

Was this an intentional difference in the display? Ideally I think this should show directly under the H2 because if we are combining the Q&As then the intro should apply to all of these as well. But let me know if that is not possible and I can create a new ticket for this to determine behavior based on technical feasibility.

**Comment by randimays** [comment]
> @randimays I am realizing we discussed the header but not the intro field and so it seems to be handled differently:
> 
> * In scenario 1 (Reusable header but the Q&As are not displaying as accordions) we are showing this in the middle
> * In scenarios 3 + 4 (Reusable Q&As are showing as accordions) we aren't showing this at all
> 
> Was this an intentional difference in the display? Ideally I think this should show directly under the H2 because if we are combining the Q&As then the intro should apply to all of these as well. But let me know if that is not possible and I can create a new ticket for this to determine behavior based on technical feasibility.

@laflannery I didn't add introductions to all of the CLPs for testing as that section is also optional. The fraud, action center, and flu CLPs have intros but the trust one does not.

I'll add the intro under the header (if it exists) and get this updated!

**Comment by randimays** [comment]
@laflannery This is ready for your review please

**Review by laflannery — APPROVED** [review]
Looks good

**Pull request merged**
