### PR TITLE
add back-to-top to med records template

### PR DESCRIPTION
**Pull request by jtmst**
**Note**: Delete the description statements, complete each step. **None are optional**, but can be justified as to why they cannot be completed as written. Provide known gaps to testing that may raise the risk of merging to production.

## Summary

- Adds back-to-top va web component to the vamc medical records template

## Related issue(s)

https://github.com/department-of-veterans-affairs/va.gov-cms/issues/16960

## Testing done

- ran local test suite

## Screenshots

image
image

## What areas of the site does it impact?
VAMC medical records pages

*(Describe what parts of the site are impacted **if** code touched other areas)*

### Quality Assurance & Testing

- [ ] I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [ ] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs
- [ ] Linting warnings have been addressed
- [ ] Documentation has been updated ([link to documentation](#) \*if necessary)
- [ ] Screenshot of the developed feature is added
- [ ] [Accessibility testing](https://depo-platform-documentation.scrollhelp.site/developer-docs/wcag-2-1-success-criteria-and-foundational-testing) has been performed

### Error Handling

- [ ] Browser console contains no warnings or errors.
- [ ] Events are being sent to the appropriate logging solution
- [ ] Feature/bug has a monitor built into Datadog or Grafana (if applicable)

### Authentication

- [ ] Did you login to a local build and verify all authenticated routes work as expected with a test user

### :warning: Team Sites (only applies to modifications made to the VA.gov header) :warning:

- [ ] The header does not contain any web-components
- [ ] I used the [proxy-rewrite steps](https://github.com/department-of-veterans-affairs/vets-website/tree/main/src/applications/proxy-rewrite#local-dev) to test the injected header scenario
- [ ] I reached out in the `#sitewide-public-websites` Slack channel for questions

## Requested Feedback

(OPTIONAL) _What should the reviewers know in addition to the above. Is there anything specific you wish the reviewer to assist with. Do you have any concerns with this PR, why?_

### CODE REVIEW

**Review by laflannery — APPROVED** [review]
LGTM

**Review by randimays — APPROVED** [review]

**Review by eselkin — APPROVED** [review]
Correct placement. LGTM

**Comment by thejordanwood** [comment]
@jtmst I'm noticing that the back to top component has more spacing between it and the feedback component when it's resting at the bottom of the page. Is there a way that it could have the same spacing as benefit pages? [This is an example](https://www.va.gov/health-care/about-va-health-benefits/your-care-team/) of what it looks like on a benefit page. 

This is what I see in the PR:

Screenshot 2024-05-07 at 1 46 43 PM

Ideally it would look like this:

Screenshot 2024-05-07 at 1 49 56 PM

**Comment by eselkin** [comment]
That must have something to do with putting it inside the article. We do always include it in the `<article>` in past pages, but maybe there's some additional spacing on this article?

**Comment by thejordanwood** [comment]
Spacing looks good now. Thanks for fixing that @jtmst!

**Pull request merged**
