### PR TITLE
Removed transformer code

### PR DESCRIPTION
**Pull request by timwright12**
## Description
Clean up task to remove the old transformers code from content-build

## Testing done
Running build and checking the rendered site. Would love it if someone on the PR could pull it locally and click around as well

### CODE REVIEW

**Review by kelsonic — APPROVED** [review]
Yayyyy! 🎉

**Review by theodur — APPROVED** [review]
I think we can also delete `script/copy-entities.js`. Other than that, everything looks good! The site works fine locally.

**Comment by timwright12** [comment]
@theodur thanks! I was actually wondering about that file

**Comment by theodur** [comment]
No problem! That script was mostly used for testing on entities from the CMS export. There's more context [here](https://github.com/department-of-veterans-affairs/vets-website/pull/11250).

**Review by mpelzsherman — CHANGES_REQUESTED** [review]
Thank you so much for doing this!

Please also search and destroy all instances of the `useTomeSync` variable.

I agree with @theodur that this file can also be removed:

`script/copy-entities.js`

**Comment by timwright12** [comment]
@theodur @mpelzsherman pulled out the copy-entities.js script, but I'm going to reach out to CMS for instances of `useTomeSync` as it seems like they're all really tied into the queries, which is a bit outside the, "delete this and it'll be fine," patterns in the rest of the PR so I want someone more familiar with the code to look at it

**Review by mpelzsherman — APPROVED** [review]
If you want to remove `useTomeSync` in a separate PR, that's fine by me.

Looks to me like you might could just `git revert 532dfd5cfaa7e4b95b3aaffb394f97d2d69acd0a` though:

https://github.com/department-of-veterans-affairs/content-build/commit/532dfd5cfaa7e4b95b3aaffb394f97d2d69acd0a

**Review by jhonnyoddball — APPROVED** [review]
LGTM

**Comment by timwright12** [comment]
Note that I'll be opening a new PR specifically for cleaning up `useTomeSync` since this one is already really large. 

Tested this on a clean review instance deploy this morning

**Pull request merged**
