### PR TITLE
VACMS-15717: Change reusable Q&As header structure  

### PR DESCRIPTION
**Pull request by chriskim2311**
**Note**: Delete the description statements, complete each step. **None are optional**, but can be justified as to why they cannot be completed as written. Provide known gaps to testing that may raise the risk of merging to production.

## Summary
For this ticket we addressed header tags for accordions based on if we have a header title or not. There were multiple implementations of these reusable Q&As so we created tugboat content for each. 

```
 FAQs
 Resources & Support
 Benefit Detail Pages
 CLPs
```

## Related issue(s)
https://github.com/department-of-veterans-affairs/va.gov-cms/issues/15717

## Testing done
Tugboat Env: main-dyel3cg3kniaoc6nrizjhqazkfgueref.demo.cms.va.gov/

CLP: https://web-dyel3cg3kniaoc6nrizjhqazkfgueref.demo.cms.va.gov/initiatives/this-is-my-clp
FAQs: https://web-dyel3cg3kniaoc6nrizjhqazkfgueref.demo.cms.va.gov/resources/test-faq-page
Resources & Support: https://web-dyel3cg3kniaoc6nrizjhqazkfgueref.demo.cms.va.gov/resources/r-s-detail-page
Benefit Detail Pages:  https://web-dyel3cg3kniaoc6nrizjhqazkfgueref.demo.cms.va.gov/benefits-detail

## What areas of the site does it impact?

*(Describe what parts of the site are impacted **if** code touched other areas)*

## Acceptance criteria
- [ ] Test Reusable Q&As across multiple content types.
- [ ] A11y review

### Quality Assurance & Testing

- [ ] I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [ ] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs
- [ ] Linting warnings have been addressed
- [ ] Documentation has been updated ([link to documentation](#) \*if necessary)
- [ ] Screenshot of the developed feature is added
- [ ] [Accessibility testing](https://depo-platform-documentation.scrollhelp.site/developer-docs/wcag-2-1-success-criteria-and-foundational-testing) has been performed

### CODE REVIEW

**Review by randimays — APPROVED** [review]
LGTM!

**Comment by laflannery** [comment]
These look good, however, per discussion with with @chriskim2311 I think we may need to rethink/rework the CLP headers when we looked at [this other ticket](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/10940)

**Comment by laflannery** [comment]
@maxx1128 I don't understand the question? However I can tell you that this is fake content - does that help answer your question?

**Comment by maxx1128** [comment]
@laflannery My question is whether the circled headers should be `h2` or `h3` headers. The fact that it's fake data makes it harder for me to tell if them being `h2`s was purposeful or accidental.

**Comment by laflannery** [comment]
They should be H2s - I reviewed these pages previously and the header structure is now all correct, pending the [comment I left before](https://github.com/department-of-veterans-affairs/content-build/pull/1845#issuecomment-1883495670)

**Review by maxx1128 — APPROVED** [review]

**Review by CBonade — APPROVED** [review]

**Pull request merged**
