### PR TITLE
VACMS-18659: Update clp node to be able to use url for field links

### PR DESCRIPTION
**Pull request by chriskim2311**
## Summary
For this PR we are introducing URL paths when available for CLP field links when referencing internal links. We will defer back to URI if there is no URL available. 

Changes for field links are made for the following fields in CLPs:
What you can do 
Spotlight
Stories

## Related issue(s)
https://github.com/department-of-veterans-affairs/va.gov-cms/issues/18659

## Testing done
Tested in tugboat instance

CMS: https://main-jk4uouhulv1tbvo6a4fqxpyyjvjnazmf.ci.cms.va.gov/initiatives/prepare-for-vas-secure-sign-in-changes

Review Instance : https://main-jk4uouhulv1tbvo6a4fqxpyyjvjnazmf.ci.cms.va.gov/initiatives/prepare-for-vas-secure-sign-in-changes?_format=static_html

## Screenshots

<details>
<summary> CMS for Stories Field Link Node </summary>
Edit_Campaign_Landing_Page_Prepare_for_VA’s_secure_sign-in_changes___VA_gov_CMS
</details>

<details>
<summary>Stories Field Link URL</summary>
Prepare_For_VA’s_Secure_Sign-In_Changes___Veterans_Affairs
</details>

<details>
<summary>Stories Field Link graphQL</summary>
Prepare_For_VA’s_Secure_Sign-In_Changes___Veterans_Affairs
</details>
 
<details>
<summary>CMS for What you can do Field Link Node</summary>
Edit_Campaign_Landing_Page_Prepare_for_VA’s_secure_sign-in_changes___VA_gov_CMS
</details>
 

<details>
<summary>What you can do Field Link URL and graphQL</summary>
Prepare_For_VA’s_Secure_Sign-In_Changes___Veterans_Affairs
Prepare_For_VA’s_Secure_Sign-In_Changes___Veterans_Affairs
</details>
 

## What areas of the site does it impact?
CLPs

## Acceptance criteria

- [x] Linked node IDs direct to the correct live VA.gov page or trigger a 403

### Quality Assurance & Testing

- [ ] I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [ ] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs
- [ ] Linting warnings have been addressed
- [ ] Documentation has been updated ([link to documentation](#) \*if necessary)
- [x] Screenshot of the developed feature is added
- [ ] [Accessibility testing](https://depo-platform-documentation.scrollhelp.site/developer-docs/wcag-2-1-success-criteria-and-foundational-testing) has been performed

### Error Handling

- [x] Browser console contains no warnings or errors.
- [ ] Events are being sent to the appropriate logging solution
- [ ] Feature/bug has a monitor built into Datadog or Grafana (if applicable)

### CODE REVIEW

**Comment by laflannery** [comment]
@chriskim2311 I'm building this on my tugboat because I want to test something else but for right now I have one question on the What you can do section:
- The second 2 items have full URLs in the CMS but on the Front end they are going to dev.va URLs, that seems weird. Wouldn't they go to the main prod site because of the URL in Drupal?
**CMS**
image

**Front end**
image

**Comment by laflannery** [comment]
@chriskim2311 My tugboat eventually publishing and I see no other issues. If we can just investigation my previous question and figure out why it's pulling dev instead of the full URL that's the only issue I see

**Review by eselkin — APPROVED** [review]
code/queries lgtm

**Review by randimays — APPROVED** [review]
LGTM!

**Pull request merged**
