### PR TITLE
74399 rename to arp and representative

### PR DESCRIPTION
**Pull request by williamphelps13**
## Summary

- Purpose
  - There are a number of places we are using `reps` or `representatives` across the code bases
  - As a team we decided the subdomain should be representative.va.gov and as such uses of `reps` or `representatives` (plural) should be renamed to `rep` or `representative` (singular)
  - In addition, the portal within this subdomain now has a name - Accredited Representative Portal. As such, there are cases where `representatives` should actually be changed to `accredited-representative-portal` 
- This is step 3 of a platform recommended way to update an entryFile/entryName of an application ([source](https://dsva.slack.com/archives/C04868KS69L/p1710526246855809?thread_ts=1710526225.599819&cid=C04868KS69L)):
    1.  Keep the existing application in vets-website the way it is (so that content-build will continue working) - [PR](https://github.com/department-of-veterans-affairs/vets-website/pull/28477)
    2. Create a copy of the application with the desired entryName in the manifest and a new rootUrl (this is temporary) and get that merged - [PR](https://github.com/department-of-veterans-affairs/vets-website/pull/28672)
    3. In content-build, add a new entry to registry.json for the app copy
    4. Once you have confirmed that this is all working in prod / staging, you can update the entries in content-build to swap the urls (so new entry in content-build has the permanent URL, old entry has the temporary one) - [PR](https://github.com/department-of-veterans-affairs/content-build/pull/1957/files)
    5. Once the swap has happened and been confirmed to be working, you can remove the old entry from content-build and the old app from vets-
- Team: Benefits Accredited Representative Facing Team

## Related issue

[#74399 Rename to representative / accredited-representative-portal](https://app.zenhub.com/workspaces/accredited-representative-facing-team-65453a97a9cc36069a2ad1d6/issues/gh/department-of-veterans-affairs/va.gov-team/74399)

#### vets-website
- [74399 ARF - Rename to arp and representative](https://github.com/department-of-veterans-affairs/vets-website/pull/28477)
- [74399 ARF - Create app copy named arp](https://github.com/department-of-veterans-affairs/vets-website/pull/28672)

#### vagov-content
- [Revert "72956 add accredited representative page (#903)"](https://github.com/department-of-veterans-affairs/vagov-content/pull/915)

### CODE REVIEW

**Comment by jamigibbs** [comment]
@williamphelps13 I see there's an [error here](https://github.com/department-of-veterans-affairs/content-build/actions/runs/8254957450/job/22585050407?pr=1957) from content-build saying that a file it's looking for doesn't exist:

```
Step 36 of 54 start: Apply layouts R

[MANUAL GC] heapUsed: 974.17mB (466.73mB collected) rss: 4134.14mB (47.63mB collected)

/home/runner/runner1/_work/content-build/content-build/content-build/src/site/stages/build/plugins/download-assets.js:11
  throw up;
  ^

[Error: ENOENT: no such file or directory, open '/home/runner/runner1/_work/content-build/content-build/content-build/src/site/layouts/representative.html'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/home/runner/runner1/_work/content-build/content-build/content-build/src/site/layouts/representative.html'
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Error: Process completed with exit code 1.
```

Have you tested running this branch locally with `vetes-website` and the `content-build` main branch running as well?

**Comment by jamigibbs** [comment]
> I updated that missing file `representative.html` in this PR to be `accredited-representative-portal.html`

Is it necessary to change that file name? Otherwise, looking at the PR history of that file, there is another place it's being referenced here that might be related: https://github.com/department-of-veterans-affairs/vagov-content/pull/903/files

**Review by emily-gullo — APPROVED** [review]
After lint fixes mentioned, LGTM!

**Review by randimays — APPROVED** [review]
LGTM

**Review by eselkin — COMMENTED** [review]
LGTM. Seems to cover all app bases.

**Pull request merged**
