### PR TITLE
Remove Event page queries from Content Build

### PR DESCRIPTION
**Pull request by timcosgrove**
Currently a test: put into PR form to test CI and on Tugboat against CMS. 

## Summary

This removes Event and Event Listing pages from being output by Content Build. Broadly, this has 2 parts:
- remove the queries, including removing Events from the node count queries
- update the broken link checker to ignore Event pages, since they are no longer available to be checked

Events are being removed because they are now deployed to production by Next Build. 

## Related issue(s)

https://github.com/department-of-veterans-affairs/va.gov-cms/issues/19811

## Testing done

- Multiple content-releases on Tugboat using this branch
  - Tested that output completed successfully
  - Tested that Event & Event Listings were not included
  - Tested that pages that incorporate Events within them do still render correctly
  - Checked that the broken link check is not affected by the removal

## QA steps
This was built on this Tugboat instance: https://main-jhfxzor0fzbac0tpmbor1dbj6qgizfwj.demo.cms.va.gov/admin/content/deploy
- [ ] Check that output completed successfully

Front-end is here: https://web-jhfxzor0fzbac0tpmbor1dbj6qgizfwj.demo.cms.va.gov/
Investigate that output looks normal. It largely should. The main thing to be careful of is Events not being there. 

Here is an example VAMC: https://web-jhfxzor0fzbac0tpmbor1dbj6qgizfwj.demo.cms.va.gov/manchester-health-care/
- [ ] You should have Events down the page: https://web-jhfxzor0fzbac0tpmbor1dbj6qgizfwj.demo.cms.va.gov/manchester-health-care/
- [ ] The individual events should show a 404 if you try to click through.
- [ ] 'See all Events' on this page should show a 404.
- [ ] Clicking 'Events' in the sidebar should result in a 404. 
- [ ] Clicking in other sidebar menu items like 'News releases' should click through.
- [ ] Examine the build output for this preview: https://main-jhfxzor0fzbac0tpmbor1dbj6qgizfwj.demo.cms.va.gov/sites/default/files/build.txt
- [ ] It should not show broken links related to Events.
- [ ] The build should have completed without errors.

### CODE REVIEW

**Review by eselkin — APPROVED** [review]
LGTM.

**Comment by eselkin** [comment]
I would get @randimays for a second opinion though.

**Review by chriskim2311 — APPROVED** [review]
LGTM!

**Review by anantais — APPROVED** [review]

**Review by randimays — COMMENTED** [review]
Should this also include the `event_listing.drupal.liquid` and `event.drupal.liquid` templates?

**Review by powellkerry — APPROVED** [review]

**Pull request merged**
