### PR TITLE
top tasks and link v3 migration

### PR DESCRIPTION
**Pull request by jtmst**
**Note**: Delete the description statements, complete each step. **None are optional**, but can be justified as to why they cannot be completed as written. Provide known gaps to testing that may raise the risk of merging to production.

## Summary

- adds top of page component to register for care template
- switches facility name to use va-link component
- remove extra spacing for on this page component on mobile

## Related issue(s)

- https://github.com/department-of-veterans-affairs/va.gov-cms/issues/16957
## Testing done

- Local testing
- `/minneapolis-health-care/billing-and-insurance/`
- `/minneapolis-health-care/medical-records-office/`
- `/boston-health-care/register-for-care/`

## Screenshots

image
image
image
 
image

## What areas of the site does it impact?

*(Describe what parts of the site are impacted **if** code touched other areas)*

### Quality Assurance & Testing

- [ ] I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [ ] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs
- [ ] Linting warnings have been addressed
- [ ] Documentation has been updated ([link to documentation](#) \*if necessary)
- [ ] Screenshot of the developed feature is added
- [ ] [Accessibility testing](https://depo-platform-documentation.scrollhelp.site/developer-docs/wcag-2-1-success-criteria-and-foundational-testing) has been performed

### Error Handling

- [ ] Browser console contains no warnings or errors.
- [ ] Events are being sent to the appropriate logging solution
- [ ] Feature/bug has a monitor built into Datadog or Grafana (if applicable)

### Authentication

- [ ] Did you login to a local build and verify all authenticated routes work as expected with a test user

### :warning: Team Sites (only applies to modifications made to the VA.gov header) :warning:

- [ ] The header does not contain any web-components
- [ ] I used the [proxy-rewrite steps](https://github.com/department-of-veterans-affairs/vets-website/tree/main/src/applications/proxy-rewrite#local-dev) to test the injected header scenario
- [ ] I reached out in the `#sitewide-public-websites` Slack channel for questions

## Requested Feedback

(OPTIONAL) _What should the reviewers know in addition to the above. Is there anything specific you wish the reviewer to assist with. Do you have any concerns with this PR, why?_

### CODE REVIEW

**Review by maxx1128 — COMMENTED** [review]
I see where the first two points of the summary are addressed in this pull request, but where is the fixed links for the medical records office, and billing and insurance pages?

**Comment by randimays** [comment]
@maxx1128 I'm taking this over for Josh since he is on PTO. I also didn't see any code changes for fixed links. I removed this part of the description and added a point about fixing the spacing for the On this page component on mobile.

**Review by maxx1128 — APPROVED** [review]

**Comment by laflannery** [comment]
@randimays This is another case where we should make sure we encode the text string in case of the double quotes situation. I don't know if that was already done but I wanted to ask just in case. Otherwise this looks good!

**Review by laflannery — APPROVED** [review]
LGTM

**Comment by randimays** [comment]
@laflannery Thank you for proactively revisiting this PR and reviewing! I had pushed the encode changes late yesterday and was waiting for the CI to finish. For posterity, the encoding was added to the facility name:

Screenshot 2024-05-22 at 4 03 34 PM
Screenshot 2024-05-22 at 4 03 42 PM

**Pull request merged**
