### PR TITLE
Updated slack alert channels for CI and Deploy

### PR DESCRIPTION
**Pull request by timwright12**
## Description
Routing information and alerts about content-build CI and deployment status into new slack channel

## Original issue(s)
department-of-veterans-affairs/va.gov-team#30111

### CODE REVIEW

**Comment by timwright12** [comment]
@indytechcook for awareness

**Review by alexandec — APPROVED** [review]

**Comment by indytechcook** [comment]
Thanks @timwright12

**Comment by indytechcook** [comment]
Give me a bit to communicate this change out before merging.  There are quite a few people who watch that channel for the updates and broken links

**Comment by indytechcook** [comment]
@timwright12 what do you think about having different slack channels for the different responsible teams?

**Comment by indytechcook** [comment]
> Give me a bit to communicate this change out before merging. There are quite a few people who watch that channel for the updates and broken links

I see this is only on CI and daily but not the release, sorry for my misunderstanding.   With this different channel with only the CI/Deploy errors being reported, how does your team look to engage our team? Our we expected to watch both channels now?

**Comment by timwright12** [comment]
@indytechcook we can bring the content release and broken links into the new channel if you want, but since Release Tools is the point of contact for these items I don't think CMS necessarily needs to keep eyes on it

**Pull request merged**
