### PR TITLE
VACMS 16962 Adds back to top to Billing and Insurance pages

### PR DESCRIPTION
**Pull request by eselkin**
## Summary

- Adds va-back-to-top to Billing and Insurance top-task page
- Sitewide Facilities

## Related issue(s)

- https://app.zenhub.com/workspaces/sitewide-facilities-639f5253e4b702a32376339e/issues/gh/department-of-veterans-affairs/va.gov-cms/16962

## Testing done

- Manual check that DS component appears. Tested that component brings user back to top content on page in mobile and desktop.

## Screenshots

_Note: This field is mandatory for UI changes (non-component work should NOT have screenshots)._

<details>
<summary>Desktop page</summary>

</details>

<details>
<summary>Mobile page</summary>

</details>

## What areas of the site does it impact?

Billing and Insurance VAMC top-task pages

## Acceptance criteria

- [x] VA back-to-top component appears 

### Quality Assurance & Testing

- [x] I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [x] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs
- [x] Linting warnings have been addressed
- [x] Documentation has been updated ([link to documentation](#) \*if necessary)
- [x] Screenshot of the developed feature is added
- [ ] [Accessibility testing](https://depo-platform-documentation.scrollhelp.site/developer-docs/wcag-2-1-success-criteria-and-foundational-testing) has been performed

### Error Handling

- [x] Browser console contains no warnings or errors.
- [x] Events are being sent to the appropriate logging solution
- [x] Feature/bug has a monitor built into Datadog or Grafana (if applicable)

### Authentication

- [x] Did you login to a local build and verify all authenticated routes work as expected with a test user (does not affect authenticated content)

## Requested Feedback

See that component appears either in images or on RI

### CODE REVIEW

**Review by maxx1128 — APPROVED** [review]

**Comment by eselkin** [comment]
If you look at the desktop image, you'll see the spacing between the back to top and the Medallia button is larger (like it was in one of the PW fixes to this issue). Do we put the feedback button into the article like it is in the one that was cited [here](https://github.com/department-of-veterans-affairs/content-build/pull/2061#issuecomment-2099096041)?

Most pages have the spacing like this one as opposed to the one in the comment above.
@thejordanwood @laflannery

**Comment by eselkin** [comment]
I moved it, will update the image

**Comment by eselkin** [comment]
Image is updated

**Comment by thejordanwood** [comment]
Thanks @eselkin! The spacing looks good to me.

**Pull request merged**
