### PR TITLE
VACMS-13276: Fix footer social media link

### PR DESCRIPTION
**Pull request by chri5tia**
## Description

relates to https://github.com/department-of-veterans-affairs/va.gov-cms/issues/13276

## Testing done & Screenshots
TBD

## QA steps

Go to content-build on staging or a tugboat instance and click on the Social Media footer link. It should go to https://digital.va.gov/web-governance/social-media/social-media-sites/

## Acceptance criteria

- [ ]

## Definition of done
- [ ] Events are logged appropriately
- [ ] Documentation has been updated, if applicable
- [ ] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)
- [ ] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

### CODE REVIEW

**Comment by chri5tia** [comment]
I pulled in this branch into https://web-i7n92wfzswpe358hivrspihf2ntzshzp.ci.cms.va.gov/ for testing. Check back later.

**Comment by chri5tia** [comment]
Pulled this PR into a content build which you can see here for the review: https://web-i7n92wfzswpe358hivrspihf2ntzshzp.ci.cms.va.gov/

**Review by rmessina1010 — APPROVED** [review]
LGTM

**Review by maxx1128 — APPROVED** [review]
New URL and staging instance both work as expected for me.

**Review by jtmst — APPROVED** [review]

**Pull request merged**
