### PR TITLE
VACMS 16362: Make only published Vet Center Services display

### PR DESCRIPTION
**Pull request by eselkin**
## Summary

- Makes Vet Center services use the entity.status value to determine whether to show or not. Altered graphql to provide the value.
- Sitewide team

## Related issue(s)

- https://github.com/department-of-veterans-affairs/va.gov-cms/issues/16362

## Testing done

- Manually tested by archiving, archiving and drafting, drafting, services for a Vet Center location (St Louis in the tugboat associated)

## Screenshots

Not a graphical change, but a data change

## What areas of the site does it impact?

Vet Center pages, services accordions

## Acceptance criteria
- [x] The Vet Center services query filters for Published status.
    - [x] If the service isn't Published, it doesn't show on VA.gov.

### Quality Assurance & Testing

- [x] I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [x] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs
- [x] Linting warnings have been addressed
- [x] Documentation has been updated ([link to documentation](#) \*if necessary)
- [ ] Screenshot of the developed feature is added (n/a)
- [ ] [Accessibility testing](https://depo-platform-documentation.scrollhelp.site/developer-docs/wcag-2-1-success-criteria-and-foundational-testing) has been performed (no change in content)

### Error Handling

- [x] Browser console contains no warnings or errors.
- [x] Events are being sent to the appropriate logging solution
- [x] Feature/bug has a monitor built into Datadog or Grafana (if applicable)

### Authentication

- [x] Did you login to a local build and verify all authenticated routes work as expected with a test user

## Requested Feedback

Check
https://web-codylbelkq0gdivw6x7tykigmeqloewe.demo.cms.va.gov/st-louis-vet-center

On that tugbot 

I've archived [Addiction and substance use care](https://main-codylbelkq0gdivw6x7tykigmeqloewe.demo.cms.va.gov/st-louis-vet-center/service/st-louis-vet-center-addiction-and-substance-abuse-care)

I've archived and drafted, [Couples and family counseling](https://main-codylbelkq0gdivw6x7tykigmeqloewe.demo.cms.va.gov/st-louis-vet-center/service/st-louis-vet-center-couples-and-family-counseling)

I've archived, drafted, and approved [Community engagement](https://main-codylbelkq0gdivw6x7tykigmeqloewe.demo.cms.va.gov/st-louis-vet-center/service/st-louis-vet-center-community-engagement)

But check that none of those 3 should be showing.

### CODE REVIEW

**Comment by eselkin** [comment]
I'll check the logic. I don't know if it doesn't show if there are none. I'll add that if it doesn't exist. The id seems like it needs a fix though.

**Comment by eselkin** [comment]
@randimays it does not display the header or accordion if `servicesListOrdered.length` less than or equal 0, so that's good. I fixed the ids. I don't see the individual accordion-items having the wrong ids, those seem appropriate and correct for the items, but the accordions were definitely incorrect

**Comment by eselkin** [comment]
@randimays Oh, I know why it was coming across as mislabeled accordions (someone - me-  pulled the accordion out of the loop or something but the label only existed in the loop)... But accordions shouldn't be in the loop, only the accordion-items should be.

**Comment by jilladams** [comment]
(Randi's now out on PTO through 9/30. Will need to enlist another code reviewer here -- whether @chriskim2311 @dsasser or otherwise not sure)

**Review by chriskim2311 — APPROVED** [review]
LGTM! Tested in Tugboat and code changes look good. Nice clean up on accordion id's

**Pull request merged**
