### PR TITLE
VACMS-7009: Video link text label is not making it to the FE

### PR DESCRIPTION
**Pull request by netboss**
- Updated video link text in FE paragraph twig template.
- Adjusted video link text variable to "`{{entity.fieldTitle}}`".

## Description
Relates to https://github.com/department-of-veterans-affairs/va.gov-cms/issues/7009

and unites https://github.com/department-of-veterans-affairs/va.gov-cms/pull/7125

## QA steps

As user editor
- [ ] Go to `/houston-health-care/work-with-us/internships-and-fellowships/pharmacy-residencies/` (node 23174) to verify and confirm that the link text for the video is "**Find out more about Pharmacy Residency programs at VA Houston.**" and not "**Go to video**".

## Screenshots
VACMS-7009-video-link-text-fixed

## Acceptance criteria
- [ ]

## Definition of done
- [ ] Events are logged appropriately
- [ ] Documentation has been updated, if applicable
- [ ] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)
- [ ] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

### CODE REVIEW

**Review by jhonnyoddball — APPROVED** [review]

**Review by swirtSJW — COMMENTED** [review]
@netboss  There are no testng steps and no screenshot showing that this worked.  Can you provide them?

**Comment by netboss** [comment]
> @netboss There are no testng steps and no screenshot showing that this worked. Can you provide them?

@swirtSJW I'm having hard time testing this on the frontend in tugboat. This is still showing the "Go to video" link text: https://web-f5egnpebc8n9mrhd0jmfsgqcejytvwno.ci.cms.va.gov/houston-health-care/work-with-us/internships-and-fellowships/pharmacy-residencies/ -- How (or where) can I test this on the frontend?

**Review by swirtSJW — CHANGES_REQUESTED** [review]
@netboss this is not working.

Here is what I did
image
In the tugboat environment for you CMS PR go to the content release page then do 1,2,and 3 to point it to your content-build PR.

Then wait until that content release has happened, then look at the page 
image

The link to the video is not working because that link text is not coming through

image

Two possible points of failure:
1) `entity.fieldMedia.fieldTitle`  is not the right name of the thing you are trying to get (the link title)
2)  `entity.fieldMedia.fieldTitle` is not in the graphQL query so it is not being returned by the query, so it is not available to the template

**Comment by swirtSJW** [comment]
@netboss The data is there.  So the graphQL query is not to blame.  You can see it here in the js contentData object (which is available on all lower environments, just not prod)
image

In that contentData you can see that you are trying to grab the title from a place it does not exists.  `fieldTitle` is not inside fieldMedia where you are grabbing `entity.fieldMedia.fieldTitle`    fieldTitle is at the same level as fieldMedia.

**Review by swirtSJW — APPROVED** [review]
Tests out ok in tugboat content-build   (though there are no user: editors on the FE)

**Pull request merged**
