### PR TITLE
Update vet center styles to use VADS

### PR DESCRIPTION
**Pull request by gescobardev**
## Description
Resolves issue linked below

### CODE REVIEW

**Review by mpelzsherman — APPROVED** [review]

**Review by mpelzsherman — CHANGES_REQUESTED** [review]
On closer inspection of the [review environment,](http://5121e24a2924408dfef45af2dbda8d55.review.vetsgov-internal/escanaba-vet-center/) I am seeing a few differences from the original design that should probably be addressed.

Please see screen shots and work with @lildziner or @nicko-amida  to identify which changes are OK, and which need to be corrected.

**Comment by mpelzsherman** [comment]
Escanaba_Vet_Center___Veterans_Affairs

**Comment by lildziner** [comment]
the preference would be for the “single spacing” between the bullets and equal margin above and below the divider line. There are a few variations of the in the spotlight box out there and all a little different. This might be a good reference for the bullet spacing and this one for margin height above/below divider

**Comment by mpelzsherman** [comment]
Looks good to me locally - just resolve the conflict and we should be good to go! We should confirm in the review environment though.

**Review by mpelzsherman — APPROVED** [review]

**Pull request merged**
