### PR TITLE
VA-15567: Remove Top Task Links for Programs pages

### PR DESCRIPTION
**Pull request by maxx1128**
## Summary

This removes top task links from the Programs pages.

Facilities team.

## Related issue(s)

- _Link to ticket created in va.gov-cms repo_
department-of-veterans-affairs/va.gov-cms#15567

## Testing done

Locally, visual testing.

- https://web-txcrk8bym4a0ivw3xfr8xvdhezmls36f.demo.cms.va.gov/chicago-health-care/programs/covid-19-vaccines/jesse-brown-va-post-acute-sequelae-of-covid-19-long-covid-program/
- https://web-txcrk8bym4a0ivw3xfr8xvdhezmls36f.demo.cms.va.gov/lovell-federal-health-care-tricare/programs/immunizations/

## Screenshots

Screen Shot 2024-03-22 at 10 34 02 AM
Screen Shot 2024-03-22 at 10 33 43 AM

## What areas of the site does it impact?

All Programs pages, including Lovell.

### Quality Assurance & Testing

- [x] I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [x] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs
- [x] Linting warnings have been addressed
- [x] Documentation has been updated ([link to documentation](#) \*if necessary)
- [x] Screenshot of the developed feature is added
- [ ] [Accessibility testing](https://depo-platform-documentation.scrollhelp.site/developer-docs/wcag-2-1-success-criteria-and-foundational-testing) has been performed

### Error Handling

- [x] Browser console contains no warnings or errors.
- [x] Events are being sent to the appropriate logging solution
- [x] Feature/bug has a monitor built into Datadog or Grafana (if applicable)

### Authentication

- [x] Did you login to a local build and verify all authenticated routes work as expected with a test user

### CODE REVIEW

**Comment by eselkin** [comment]
@maxx1128 I think there's some miscommunication here. @mmiddaugh It's remove the 3 top-task action links (i.e. Make an appt/View all health services/etc) from the pages not the side nav, right?

**Comment by maxx1128** [comment]
> @maxx1128 I think there's some miscommunication here. @davidmpickett @mmiddaugh It's remove the 3 top-task action links (i.e. Make an appt/View all health services/etc) from the pages not the side nav, right?

@eselkin, I think I did completely misinterpret the purpose of the ticket; that's my bad entirely 😅 I'll update this pull request right away.

**Comment by eselkin** [comment]
No problem, I've totally done that.

**Comment by thejordanwood** [comment]
I can't get the styling in the tugboat links to show and am reviewing from the screenshots you have here. This looks good to me!

**Review by eselkin — APPROVED** [review]
LGTM. It's nice when there's a liquid thing that does exactly what we need.

**Pull request merged**
