### PR TITLE
[VA-14947] Add Banners to VBA Facility Query

### PR DESCRIPTION
**Pull request by maxx1128**
## Summary

This pull request adds recent banner fields to the VBA Facility Query.

## Related issue(s)

- _Link to ticket created in va.gov-cms repo_
[department-of-veterans-affairs/va.gov-cms#14947](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/14947)

## Testing done

In test environment, confirming the data is now present and build is successful.

## Screenshots

N/A

## What areas of the site does it impact?

The VBA Facility pages, but nothing visible.

### Quality Assurance & Testing

- [x] I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [x] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs
- [x] Linting warnings have been addressed
- [x] Documentation has been updated ([link to documentation](#) \*if necessary)
- [x] Screenshot of the developed feature is added
- [x] [Accessibility testing](https://depo-platform-documentation.scrollhelp.site/developer-docs/wcag-2-1-success-criteria-and-foundational-testing) has been performed

### Error Handling

- [x] Browser console contains no warnings or errors.
- [x] Events are being sent to the appropriate logging solution
- [x] Feature/bug has a monitor built into Datadog or Grafana (if applicable)

### CODE REVIEW

**Review by chriskim2311 — APPROVED** [review]
LGTM

**Review by eselkin — APPROVED** [review]
LGTM, but does this merge to main or to the other branch with VBA stuff.

**Comment by jilladams** [comment]
I'm not 100% certain, but it seems like this could merge to main? 

VBA merged PRs include other GraphQL queries, most of the templating / styling, etc: https://github.com/department-of-veterans-affairs/content-build/pulls?q=is%3Apr+vba+is%3Aclosed.  (If you see anything here that raises the hairs on your neck / shouldn't have been merged for reasons, let's discuss! )

Vs. Open VBA PRs: https://github.com/department-of-veterans-affairs/content-build/pulls?q=is%3Apr+vba+is%3Aopen

**Review by eselkin — CHANGES_REQUESTED** [review]
this also needs:
`fieldAlertType`

**Review by eselkin — APPROVED** [review]
lgtm

**Pull request merged**
