### PR TITLE
VACMS-17654 VAMC Facilities web components

### PR DESCRIPTION
**Pull request by randimays**
## Summary
Add v1 and v3 web components to VAMC Facility pages where possible. Also changes the Spotlight section to follow the Related Links pattern.

## Related issue(s)
- https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17654

## Testing done
Tested the following routes locally:
- /boston-health-care/locations/jamaica-plain-va-medical-center
- /minneapolis-health-care/locations/minneapolis-va-medical-center/
- /central-texas-health-care/locations/cedar-park-va-clinic/
- /columbia-south-carolina-health-care/locations/wm-jennings-bryan-dorn-department-of-veterans-affairs-medical-center/
- /southern-nevada-health-care/locations/southwest-las-vegas-va-clinic/
- /pacific-islands-health-care/locations/spark-m-matsunaga-department-of-veterans-affairs-medical-center/

## Screenshots

<details><summary>Social media icons (Get updates section)</summary>

### Desktop
Screenshot 2024-05-16 at 2 03 22 PM
Screenshot 2024-05-16 at 2 17 51 PM

### Mobile
Screenshot 2024-05-20 at 2 06 13 PM

</details>

<details><summary>Service locations icons / cards</summary>
Screenshot 2024-05-16 at 11 47 51 AM
Screenshot 2024-05-16 at 2 19 33 PM

### Desktop
Screenshot 2024-05-20 at 2 07 17 PM

### Mobile
Screenshot 2024-05-20 at 2 06 02 PM

</details>

<details><summary> Spotlight -> Related links</summary>

### Desktop
Screenshot 2024-05-16 at 1 57 09 PM
Screenshot 2024-05-16 at 1 57 16 PM

### Mobile
Screenshot 2024-05-20 at 2 05 55 PM

</details>

### CODE REVIEW

**Comment by randimays** [comment]
@laflannery @thejordanwood The review instance hasn't been working here, but for some odd reason, you can see the changes for this PR in the related vets-website review instance: http://68b49eda4c53a7a125581eba1370b047.review.vetsgov-internal/

**Review by eselkin — COMMENTED** [review]
Code looks great. Just building to check and then will approve.

**Review by eselkin — APPROVED** [review]
LGTM

**Review by thejordanwood — APPROVED** [review]

**Comment by laflannery** [comment]
@randimays I got this RI to work so I'm continuing to review here:
- The `<va-card>` component got added to the non-clinical services which it shouldn't be, there should be no border on these pages. For some reason it looks like the `nonClinical` conditional isn't being respected. Not sure if Eli would need to be pulled in here or not.
  - Correct display on Prod with no card
    - https://www.va.gov/boston-health-care/medical-records-office/
    - https://www.va.gov/boston-health-care/billing-and-insurance/
    - https://www.va.gov/boston-health-care/register-for-care/
  - Incorrect display on PR with card
    - http://6c11ef06dd83c185484807a5f4b943d3.review.vetsgov-internal/boston-health-care/medical-records-office/
    - http://6c11ef06dd83c185484807a5f4b943d3.review.vetsgov-internal/boston-health-care/billing-and-insurance/
    - http://6c11ef06dd83c185484807a5f4b943d3.review.vetsgov-internal/boston-health-care/register-for-care/

**Review by jtmst — APPROVED** [review]

**Comment by randimays** [comment]
@laflannery This is ready for another review, please. Cards are no longer showing on non-clinical pages:

- http://a34a9b96e65bc5ff77dc530049edb75a.review.vetsgov-internal/boston-health-care/medical-records-office/
- http://a34a9b96e65bc5ff77dc530049edb75a.review.vetsgov-internal/boston-health-care/billing-and-insurance/
- http://a34a9b96e65bc5ff77dc530049edb75a.review.vetsgov-internal/boston-health-care/register-for-care/

**Review by laflannery — APPROVED** [review]

**Pull request merged**
