### PR TITLE
VACMS-14586 Pass Main Phone Number to VAMC Medical Records and Register for Care pages

### PR DESCRIPTION
**Pull request by maxx1128**
## Description

The facility's main phone number wasn't being properly passed to VAMC pages. This adds the main phone number to the needed query and passes it to the front end.

relates to [#14586](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/14586)

### Before

Checked at [this page](https://staging.va.gov/poplar-bluff-health-care/register-for-care/)

Screen Shot 2023-08-14 at 11 37 03 AM

### After

Screen Shot 2023-08-14 at 11 53 59 AM

## QA steps

**What needs to be checked to prove this works?** That the main phone number displayed for the facility with the header too.
**What needs to be checked to prove it didn't break any related things?** The rest of the page still renders properly.

1. On a [CMS](https://prod.cms.va.gov/node/44976)  [nonclinical service page that has the checkbox checked](http://025c10d84a8f30e36309d8f4dd52b1c8.review.vetsgov-internal/montana-health-care/medical-records-office/), Check that the main phone number is now visible
   - [x] Validate that the Main phone number and header display as expected for the facility is listed for Fort Harrison VA Medical Center
2. On a [CMS](https://prod.cms.va.gov/node/46235/edit) [non-clincal service where "use main facility"](http://025c10d84a8f30e36309d8f4dd52b1c8.review.vetsgov-internal/puget-sound-health-care/medical-records-office/) is not checked, 
   - [x] Validate American Lake VA Medical Center has only one phone number provided by the non-clinical service, not the facility.  
3. On a [CMS](https://prod.cms.va.gov/node/55362/edit) [non-clinical service that has the checkbox AND multiple phone numbers listed](http://025c10d84a8f30e36309d8f4dd52b1c8.review.vetsgov-internal/marion-health-care/medical-records-office/) 
      - [x] Validate that the section under "Marion VA Medical Center" should have 
         - a Main number , 
         - a release of information phone and 
         - a release of information FAX

## Acceptance criteria

- [x] All QA steps pass

## Definition of done
- [x] Events are logged appropriately
- [x] Documentation has been updated, if applicable
- [x] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)
- [x] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

### CODE REVIEW

**Comment by swirtSJW** [comment]
I added a QA step to check that if the Facility phone number checkbox is not checked, that it uses the phone provided by the non-clinical service and not the facility phone.

**Comment by swirtSJW** [comment]
I am not seeing this phone number on the PR environment
http://025c10d84a8f30e36309d8f4dd52b1c8.review.vetsgov-internal/montana-health-care/medical-records-office/
image

**Comment by swirtSJW** [comment]
@maxx1128 I added links to three different type of pages to check in the pr environment and the validation needed.    I may be missing something but it seem like only one of the three cases pass.

**Review by swirtSJW — CHANGES_REQUESTED** [review]
I am not getting passing QA on the PR environment.

**Comment by maxx1128** [comment]
I checked this locally and on tugboat, for the three QA instances:

1. For [Fort Harrison VA Medical Center](https://web-txcrk8bym4a0ivw3xfr8xvdhezmls36f.demo.cms.va.gov/montana-health-care/medical-records-office/), main phone number is visible as expected
2. For [Seattle VA Medical Center](https://web-txcrk8bym4a0ivw3xfr8xvdhezmls36f.demo.cms.va.gov/puget-sound-health-care/medical-records-office/), main phone number is not visible as expected
3. For [North Las Vegas VA Medical Center](https://web-txcrk8bym4a0ivw3xfr8xvdhezmls36f.demo.cms.va.gov/southern-nevada-health-care/medical-records-office/), all the numbers are visible except for the main phone number, but all should be visible. The main number is still there and the “use main number” checkbox is true, so that part still needs work.

Screen Shot 2023-08-15 at 4 44 18 PM
Screen Shot 2023-08-15 at 4 44 24 PM
Screen Shot 2023-08-15 at 4 44 30 PM

**Comment by maxx1128** [comment]
Pull request now passes [the third QA criteria here.](https://web-txcrk8bym4a0ivw3xfr8xvdhezmls36f.demo.cms.va.gov/southern-nevada-health-care/medical-records-office/)

Screen Shot 2023-08-15 at 6 18 01 PM

**Comment by jilladams** [comment]
Same here -- Max is out for 3 days, this PR is theoretically good to go, per his note above, but we need sign off. I've also added @eselkin explicitly for code review, as he's not yet in the Facilities frontend team, so not getting the pings for code reviews otherwise. Let's plan to regroup on this at the early end of sprint planning.

**Review by eselkin — APPROVED** [review]
Makes use of the fieldPhoneNumber field. Looks good and covers areas where phone number is used.

**Review by swirtSJW — CHANGES_REQUESTED** [review]
I am seeing a failure on the third QA set
image

#2 passes 
image

**Comment by eselkin** [comment]
I see positive condition: `https://web-txcrk8bym4a0ivw3xfr8xvdhezmls36f.demo.cms.va.gov/san-francisco-health-care/register-for-care/` where all show

Screenshot 2023-08-16 at 4 32 51 PM


Main Phone does appear in details about the `https://web-txcrk8bym4a0ivw3xfr8xvdhezmls36f.demo.cms.va.gov/san-francisco-health-care/locations/san-francisco-va-medical-center/`

Screenshot 2023-08-16 at 4 34 15 PM

On Fort Harrison, I'm seeing the main phone where you didn't @swirtSJW 
`https://web-txcrk8bym4a0ivw3xfr8xvdhezmls36f.demo.cms.va.gov/montana-health-care/medical-records-office/`

Screenshot 2023-08-16 at 4 37 34 PM

I'm seeing them also on `https://web-txcrk8bym4a0ivw3xfr8xvdhezmls36f.demo.cms.va.gov/marion-health-care/medical-records-office/` where you didn't see them on that internal test URL.

Screenshot 2023-08-16 at 4 45 50 PM

I'm wondering if there's some difference between the URLs you and Max are using. 
Does the internal reference URL you're using update with the most recent commit he made or only the one Max posted? I wonder if that internal one is not getting the most recent commit of the 2 commits on the PR.

**Comment by swirtSJW** [comment]
I am going to trigger a rebuild of the FE for the links I used so that I can make sure it is using the tip of Max's branch.

**Comment by swirtSJW** [comment]
I think the confusion on testing is: 
- The QA steps in the body of the ticket should be the source of truth.  They are referencing the review instance for this PR. Those are what I was using to QA this and they were failing.
- The QA steps in Max's comments reference a tugboat environment. https://web-txcrk8bym4a0ivw3xfr8xvdhezmls36f.demo.cms.va.gov  which is Max's "personal" tugboat.  The problem is that environment is the same one we are using to test #1653.   It can only be built from one PR at a time, so when we build it with this PR, then it fails testing on #1653 and when we build it with 1653, it fails testing on this PR.   We should not be using the same tugboat to test both PRs.
- We need to be able to rely on the Review instances that are actually created as part of this PR.   If they get stuck, we need to figure out how to unstick them so the build correctly.   I am sure there is a method to it, but this repo isn't my home so I don't know the trick to do it. (I am sure one of our FE engineers on Public websites could help with that.

**Comment by swirtSJW** [comment]
I tried to trigger a new deployment via github action.  Will have to see if it worked.
image

**Comment by swirtSJW** [comment]
Still not getting the review instance
 When I request it I get this in the browser
 
image

and this in the terminal thats running SOCKS
image


I do not get that from other review instances.

**Comment by eselkin** [comment]
I'm seeing the build @swirtSJW triggered now:
http://27eb53578deea0a29ea9837101ece17a.review.vetsgov-internal/montana-health-care/medical-records-office/
However, it does not produce the desired result.
But how come this instance is not showing what Max's instance is showing?
Is it possible Max's environment has a change that isn't on github?

**Comment by swirtSJW** [comment]
Debugging the build problem is made even worse by this inconsistency.    Many of our content-builds contain a file ([BUILD.txt](https://www.va.gov/BUILD.txt)) that lives at the root of the site and gives details about when it was built, from what branch and what commit hash.

For some reason, this file does not exist on review instances 
image

**Comment by swirtSJW** [comment]
Thats great @eselkin .  Based on your QA, go ahead and check the remaining boxes under the QA steps at the top of the ticket, then go ahead and merge.

**Review by swirtSJW — APPROVED** [review]
Tested and approved

**Comment by jilladams** [comment]
@department-of-veterans-affairs/va-platform-cop-frontend this is now ready for review.

**Review by powellkerry — APPROVED** [review]

**Comment by jilladams** [comment]
Woo! Scheduled a Slack message to Max in #sitewide-facilities to merge on Monday, so we don't have to worry about any weekend OOB weird stuff.

**Comment by eselkin** [comment]
Changing content-build PR base for the tugboat deployment. No longer look to the QA tugboat used here to corroborate this PR.

**Pull request merged**
