### PR TITLE
Add role=list

### PR DESCRIPTION
**Pull request by kelsonic**
## Description
**Issue:** https://github.com/department-of-veterans-affairs/va.gov-team/issues/25005

This PR adds `role="list"` to all `ul` tags that have the class `usa-unstyled-list`.

## Related PRs

https://github.com/department-of-veterans-affairs/content-build/pull/410
https://github.com/department-of-veterans-affairs/vets-website/pull/18082

## Acceptance criteria
- [x] Add role="list" to all ul tags that have the class `usa-unstyled-list`

## Definition of done
- [x] Events are logged appropriately
- [x] Documentation has been updated, if applicable
- [x] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)
- [x] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

### CODE REVIEW

**Review by Rleahy22 — APPROVED** [review]

**Comment by mpelzsherman** [comment]
Changes LGTM. Once there’s a review instance to look at I'll check it out in Safari.

**Comment by mpelzsherman** [comment]
Thanks for adding this everywhere!

**Review by zacharymorel — APPROVED** [review]

**Review by mpelzsherman — APPROVED** [review]
Spot checked in Safari, looks good!

**Review by joshkimux — APPROVED** [review]
lgtm, but tagging @noahgelman here for a final check

**Comment by kelsonic** [comment]
@department-of-veterans-affairs/frontend-review-group may I have a review when you have a moment? 🙂

**Review by alexandec — APPROVED** [review]

**Pull request merged**
