### PR TITLE
event icon updated

### PR DESCRIPTION
**Pull request by jtmst**
**Note**: Delete the description statements, complete each step. **None are optional**, but can be justified as to why they cannot be completed as written. Provide known gaps to testing that may raise the risk of merging to production.

relates to https://github.com/department-of-veterans-affairs/vets-website/pull/29769

## Summary

- Updates events recurring event icon to va-icon

## Related issue(s)

- https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17822

## Testing done

- local visual

## Screenshots

image

## What areas of the site does it impact?

*(Describe what parts of the site are impacted **if** code touched other areas)*

### Quality Assurance & Testing

- [ ] I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [ ] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs
- [ ] Linting warnings have been addressed
- [ ] Documentation has been updated ([link to documentation](#) \*if necessary)
- [ ] Screenshot of the developed feature is added
- [ ] [Accessibility testing](https://depo-platform-documentation.scrollhelp.site/developer-docs/wcag-2-1-success-criteria-and-foundational-testing) has been performed

### Error Handling

- [ ] Browser console contains no warnings or errors.
- [ ] Events are being sent to the appropriate logging solution
- [ ] Feature/bug has a monitor built into Datadog or Grafana (if applicable)

### Authentication

- [ ] Did you login to a local build and verify all authenticated routes work as expected with a test user

### :warning: Team Sites (only applies to modifications made to the VA.gov header) :warning:

- [ ] The header does not contain any web-components
- [ ] I used the [proxy-rewrite steps](https://github.com/department-of-veterans-affairs/vets-website/tree/main/src/applications/proxy-rewrite#local-dev) to test the injected header scenario
- [ ] I reached out in the `#sitewide-public-websites` Slack channel for questions

## Requested Feedback

(OPTIONAL) _What should the reviewers know in addition to the above. Is there anything specific you wish the reviewer to assist with. Do you have any concerns with this PR, why?_

### CODE REVIEW

**Comment by laflannery** [comment]
@jtmst a few comments/questions:
- There is an extra `aria-hidden` attribute on the actual icon component, this isn't needed
- I noticed that some icons weren't updated but I'm also not sure if they are included in this ticket or they are accounted for in another:
  - The social icons
  - The repeat icon on the Events listing page

**Comment by jtmst** [comment]
> @jtmst a few comments/questions:
> 
> * There is an extra `aria-hidden` attribute on the actual icon component, this isn't needed
> * I noticed that some icons weren't updated but I'm also not sure if they are included in this ticket or they are accounted for in another:
>   
>   * The social icons
>   * The repeat icon on the Events listing page

Added changes for the social links.  I can also do event listings with this ticket if that makes most sense, but it needs to be a separate PR as event listings live in vets-website

**Review by randimays — APPROVED** [review]

**Comment by laflannery** [comment]
@jtmst The calendar icon shouldn't have been included here - because there is a calendar `<va-link>` option that includes the icon. That is the component that is being used currently on prod and the DST would be responsible for updating any icon within a component. Can we put that back?

Otherwise, everything else looks good

**Comment by laflannery** [comment]
No I Lied above! The Twitter logo should be using the new X logo! Do we have that available in the new va-icon set?

**Review by laflannery — APPROVED** [review]
Approved - noting that the slight misalignment of the Calendar icon and the other social icons should be resolved next week when the DST updates <va-link> to use <va-icon>

**Pull request merged**
