### PR TITLE
[VA-14942] VBA facility service content type

### PR DESCRIPTION
**Pull request by maxx1128**
## Summary

VBA Service Regions have different content types that are different "services." This pull request adds the query to bring in that data, a liquid filter to normalize and organize them, and then a partial to show them on the page template.

## Related issue(s)

[Relates to 14942.](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/14942)

## Testing done

Visual, local.

### Screenshots

_Note: This field is mandatory for UI changes (non-component work should NOT have screenshots)._

|         | After |
| ------- | ----- |
| Desktop  | Screen Shot 2023-12-18 at 4 50 53 PM |
| Mobile | Screen Shot 2023-12-18 at 4 51 02 PM |

## What areas of the site does it impact?

All VBA Region pages, which are as of yet unpublished.

*(Describe what parts of the site are impacted **if** code touched other areas)*

### Quality Assurance & Testing

- [ ] I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [x] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs
- [x] Linting warnings have been addressed
- [x] Documentation has been updated ([link to documentation](#) \*if necessary)
- [x] Screenshot of the developed feature is added
- [ ] [Accessibility testing](https://depo-platform-documentation.scrollhelp.site/developer-docs/wcag-2-1-success-criteria-and-foundational-testing) has been performed

### Error Handling

- [ ] Browser console contains no warnings or errors.
- [ ] Events are being sent to the appropriate logging solution
- [ ] Feature/bug has a monitor built into Datadog or Grafana (if applicable)

### Authentication

- [ ] Did you login to a local build and verify all authenticated routes work as expected with a test user

### :warning: Team Sites (only applies to modifications made to the VA.gov header) :warning:

- [ ] The header does not contain any web-components
- [ ] I used the [proxy-rewrite steps](https://github.com/department-of-veterans-affairs/vets-website/tree/main/src/applications/proxy-rewrite#local-dev) to test the injected header scenario
- [ ] I reached out in the `#sitewide-public-websites` Slack channel for questions

## Requested Feedback

(OPTIONAL) _What should the reviewers know in addition to the above. Is there anything specific you wish the reviewer to assist with. Do you have any concerns with this PR, why?_

### CODE REVIEW

**Review by eselkin — APPROVED** [review]
Looks great to me. Excellent testing

**Review by chriskim2311 — APPROVED** [review]
LGTM

**Comment by eselkin** [comment]
Fixed the tests after a long debugging process that should have probably only taken 10 minutes.

in liquid 
```{% assign x = regionEntities | someFunction facilityServiceEntities %}```
corresponds to calling 
```x = someFunction(regionEntities, facilityServiceEntities)```
But the test had things being fed into the liquid function as:
```x = someFunction(facilityServiceEntities, regionEntities)```
because of the order in an array for the test.

**Review by eselkin — APPROVED** [review]
LGTM and tests pass

**Pull request merged**
