### PR TITLE
VATEAM-86962: Family member benefit sidebar

### PR DESCRIPTION
**Pull request by dsasser**
## Summary
Adds sidebar for Family Member Benefits Hub.

## Related issue(s)
https://github.com/department-of-veterans-affairs/va.gov-team/issues/86962

## Testing done
Tested locally after making changes to the underlying menu structure necessary for sidebar rendering.

## Screenshots

|         | Before | After |
| ------- | ------ | ----- |
| Mobile  |    Screenshot 2024-07-03 at 11 15 42 AM | Screenshot 2024-07-03 at 11 15 53 AM  |
| Desktop |   Screenshot 2024-07-03 at 11 15 09 AM | Screenshot 2024-07-03 at 11 15 16 AM     |

## What areas of the site does it impact?
Family Member Benefits

## Acceptance criteria
- [ ] Visit https://main-cxx409f6boe4hw9loluqkm4f2kwclllf.demo.cms.va.gov/family-and-caregiver-benefits/life-insurance and ensure the sidebar is showing.
- [ ] Visit https://main-cxx409f6boe4hw9loluqkm4f2kwclllf.demo.cms.va.gov/family-and-caregiver-benefits and ensure the sidebar is NOT showing.
- [ ] Ticket ACs are met.

### Quality Assurance & Testing

- [ ] I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [ ] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs
- [ ] Linting warnings have been addressed
- [ ] Documentation has been updated ([link to documentation](#) \*if necessary)
- [ ] Screenshot of the developed feature is added
- [ ] [Accessibility testing](https://depo-platform-documentation.scrollhelp.site/developer-docs/wcag-2-1-success-criteria-and-foundational-testing) has been performed

### Error Handling

- [ ] Browser console contains no warnings or errors.
- [ ] Events are being sent to the appropriate logging solution
- [ ] Feature/bug has a monitor built into Datadog or Grafana (if applicable)

### CODE REVIEW

**Comment by jilladams** [comment]
(Drive-by AC reminder about CAIA review pre-merge.)

**Review by randimays — APPROVED** [review]
LGTM

**Review by IGallupSoCo — APPROVED** [review]
LGTM

**Comment by dsasser** [comment]
CAIA sign off: https://dsva.slack.com/archives/C01K37HRUAH/p1720202664619519?thread_ts=1719332572.216609&cid=C01K37HRUAH

**Pull request merged**
