### PR TITLE
VACMS-15318: Add Mobile Promo Banner using Smartbanner.js

### PR DESCRIPTION
**Pull request by chriskim2311**
## Summary
This PR re-introduces the smartbanner.js mobile promo banner to the site on specific pages. We are doing a soft launch of this feature to prevent issues in production while we can test against the content policies in staging. This feature will be STAGING Only and we will remove this check once we test that everything is working properly there.

## Related issue(s)
https://github.com/department-of-veterans-affairs/va.gov-cms/issues/15318

## What areas of the site does it impact?
Specific URLs on the site:
      '/health-care/refill-track-prescriptions',
      '/health-care/secure-messaging',
      '/health-care/get-medical-records',
      '/disability/view-disability-rating',
      '/claim-or-appeal-status',
      '/disability/upload-supporting-evidence',
      '/records/download-va-letters',
      '/va-payment-history',
      '/change-direct-deposit'

### CODE REVIEW

**Review by eselkin — APPROVED** [review]
lgtm

**Comment by jilladams** [comment]
@chriskim2311 I'm sure you saw, but some failing tests here that'll need a look before this can go.

**Comment by eselkin** [comment]
@chriskim2311 should rerun failing tests. The builds have been failing a lot, not sure if this is because of code freeze.

**Review by randimays — APPROVED** [review]
LGTM

**Review by ataker — APPROVED** [review]

**Pull request merged**
