### PR TITLE
Remove trailing commas in function params

### PR DESCRIPTION
**Pull request by Rleahy22**
## Description
Found while working on issue: https://github.com/department-of-veterans-affairs/va.gov-team/issues/25103
It appears that we have syntax errors in IE11 that stop JavaScript rom running due to trailing commas in function parameters: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Trailing_commas#browser_compatibility
Screen Shot 2021-08-02 at 9 57 16 AM
Screen Shot 2021-08-02 at 9 57 05 AM
I'll have to either modify the build to strip these out or remove them manually. This could be a lot of work

## Acceptance criteria
- [ ]

## Definition of done
- [ ] Events are logged appropriately
- [ ] Documentation has been updated, if applicable
- [ ] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)
- [ ] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

### CODE REVIEW

**Review by kelsonic — APPROVED** [review]
Oh wow, there's a few places we're using script tags too that don't get transpiled to es5 in the templates 😬

**Comment by Rleahy22** [comment]
> Oh wow, there's a few places we're using script tags too that don't get transpiled to es5 in the templates 😬

I found one issue in the script tags, which is now fixed

**Comment by alexandec** [comment]
Thanks for finding and fixing these! Is everything working in IE 11 now?

**Comment by Rleahy22** [comment]
> Thanks for finding and fixing these! Is everything working in IE 11 now?

I am trying to test that out, but it's been very difficult to test changes in IE11 locally or via branch deployments. If you know a good way for me to do that, that would be great!

**Comment by alexandec** [comment]
It's not perfect, but you can install VirtualBox and [Microsoft's IE11 VM](https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/) (both are free)

**Review by alexandec — APPROVED** [review]

**Pull request merged**
