### PR TITLE
VACMS-14747 Fixing duplicate IDs on accordions

### PR DESCRIPTION
**Pull request by randimays**
## Description

- https://github.com/department-of-veterans-affairs/va.gov-cms/issues/14747

When we added unique IDs to `va-accordion-item`s for linking to fragments (i.e. `/resources/the-pact-act-and-your-va-benefits/#can-i-apply-now`), it created a duplicate ID issue. The `h3`s inside of the `va-accordion-item` were automatically getting IDs assigned by `add-id-to-subheadings.js`.

Since we do not need IDs on the `h3`s inside `va-accordion-item`s, this code removes that automatic ID addition.

## Testing done & Screenshots
Tested all of the below links based on the QA steps.

## QA Steps
1. Go to one of the URLs below
2. Inspect one of the accordions
3. Note the class on the `va-accordion-item` of `"va-accordion-item"`
4. Inspect the `h3` (may or may not have `slot="headline"`) in the `va-accordion-item`
5. Note the `h3` (with or without `slot="headline"`) should not have an ID assigned to it
6. If applicable, the `On this page` section should be populated with jump links corresponding to the page headers
7. Ensure clicking on a header in `On this page` jumps to the correct header
8. Copy the URL in the bar, reload the page and try the jump link to the same header
9. Inspect the `va-accordion-item` for its ID. Use that to create a jump link (e.g. `/report-harassment/#questions-you-may-have-about-r`). Reload the page and verify it scrolls to the accordion and the accordion opens.

Positive test - these usages should have accordions with the `va-accordion-item` class and `h3`s **without** the same ID as the `va-accordion-item`.
```
# Pages that are specific to the changed templates

facility_health_service
/durham-health-care/locations/durham-va-medical-center/?_ga=2.234279389.2136479616.1692026339-137499793.1687529688

vet_centers/services
/boston-vet-center

campaign_landing_page
/initiatives/sign-in-securely-with-logingov

faq_multiple_q_a
/resources/connected-apps-faqs/

health_care_local_facility
/tennessee-valley-health-care/locations/nashville-va-medical-center/

landing_page
/decision-reviews/

vet_center
/boston-vet-center/

health_service
/durham-health-care/health-services/ 

collapsible_panel
/health-care/covid-19-vaccine/

q_a.collapsible_panel
/health-care/eligibility/ 

# Pages identified in the original ticket and/or the production issue from last week

/resources/the-pact-act-and-your-va-benefits/

/report-harassment/#questions-you-may-have-about-r

/resources/compare-va-education-benefits/

/resources/covid-19-testing-at-va/

/health-care/about-va-health-benefits/

/salt-lake-city-health-care/programs/horses-helping-veterans

/health-care/get-health-id-card/
```

### CODE REVIEW

**Review by powellkerry — APPROVED** [review]

**Review by chriskim2311 — APPROVED** [review]
LGTM

**Comment by laflannery** [comment]
I have 2 issues still existing that I feel are out of scope for this ticket and I have created separate tickets for future work:

- #14909
- #14910

The ownership of these I am unsure of (DST? PW?)

**Comment by randimays** [comment]
@laflannery I think it makes sense that PW owns both of those tickets you referenced. We control the IDs assigned to those.

**Review by maxx1128 — APPROVED** [review]
Thank you for the clear QA steps 👍 I confirmed it works for me on the test environment.

**Pull request merged**
