### PR TITLE
Update to breadcrumbs.html to use va-breadcrumbs

### PR DESCRIPTION
**Pull request by Andrew565**
## Summary

- Updating the breadcrumbs.html template file to use va-breadcrumbs
- Updated the html file to utilize a new liquid filter which handles all of the pre-processing
- I work for the Design System Team

## Related issue(s)

- Closes [DST 2945](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2945)

## Testing done

- Tested locally using unit tests (Mocha)

## Screenshots

_Note: This field is mandatory for UI changes (non-component work should NOT have screenshots)._

|         | Before | After |
| ------- | ------ | ----- |
| Mobile  |        |       |
| Desktop |        |       |

## What areas of the site does it impact?

All pages that utilize the breadcrumbs.html layout template file.

### Quality Assurance & Testing

- [X] I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [X] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs
- [X] Linting warnings have been addressed
- [X] Documentation has been updated ([link to documentation](#) \*if necessary)
- [X] Screenshot of the developed feature is added
- [X] [Accessibility testing](https://depo-platform-documentation.scrollhelp.site/developer-docs/wcag-2-1-success-criteria-and-foundational-testing) has been performed

### Error Handling

- [X] Browser console contains no warnings or errors.
- [X] Events are being sent to the appropriate logging solution
- [X] Feature/bug has a monitor built into Datadog or Grafana (if applicable)

### Authentication

- [X] Did you login to a local build and verify all authenticated routes work as expected with a test user

### CODE REVIEW

**Comment by Andrew565** [comment]
@laflannery @randimays Another breadcrumbs-related PR for you to review at your earliest convenience, please and thanks!

**Comment by randimays** [comment]
@Andrew565 Could you provide some information in the ticket description about how this was tested locally (other than unit tests)? Given that we are working with dynamic Drupal data, we should be visually verifying breadcrumbs on a handful of templates as well.

**Review by randimays — DISMISSED** [review]
@Andrew565 I reviewed one of the templates affected by these code changes and found issues.

`/pension/apply-for-veteran-pension-form-21p-527ez/introduction`

This page is missing the middle breadcrumb ("Pension benefits") that is present in prod. Also, the `VA.gov home` breadcrumb links to `/pension` instead of `va.gov`.

The below example is one entry in the `registry.json` that uses `breadcrumbs.html`. 

Screenshot 2024-09-03 at 12 59 33 PM

There are 47 total entries in the registry.json that have `"includeBreadcrumbs": true`. **I would advise you to test each application's breadcrumbs against production for regressions**. Sitewide does not own all 47 of these entries, but we're happy to try to provide guidance on how to test any application affected by your changes. Once you've tested those templates, we can review as a sanity check.

Here's some info to get you oriented:

[registry.json](https://github.com/department-of-veterans-affairs/content-build/blob/main/src/applications/registry.json) has entries for every React application in vets-website. For each entry, if the `includeBreadcrumbs` flag is true, `breadcrumbs.html` is used.

Each React app uses the [page-react.html](https://github.com/department-of-veterans-affairs/content-build/blob/main/src/site/layouts/page-react.html) template. This is indicated [in this build plugin](https://github.com/department-of-veterans-affairs/content-build/blob/d6c39ea0da9733aee5f154f5e78dd420b183d465/src/site/stages/build/plugins/create-react-pages.js#L39). `page-react.html` uses `breadcrumbs.html`.

Breadcrumbs can have several different structures coming from Drupal depending on the node type, how nested they are within other applications or flows, etc. Given that our breadcrumbs data comes from a dynamic editor-controlled environment, thorough testing is needed to identify edge cases.

**Comment by Andrew565** [comment]
Thanks for the help Randi! I'll get right on these.

**Comment by Andrew565** [comment]
@randimays This is ready for testing again, sorry for the delay while I sorted out SOCKS access.

Fixed the missing Pensions breadcrumb:
Screenshot 2024-09-26 at 12 55 02 PM

New updates look like they work elsewhere too:
Screenshot 2024-09-26 at 12 54 31 PM

**Review by randimays — CHANGES_REQUESTED** [review]
As a reminder, Sitewide does not own most of the applications affected by these changes. You need to identify the teams that own the applications and tag them on this PR for review/approval before merging. 

Recommended steps:
- search for `"includeBreadcrumbs": true` in the `registry.json` file
- cross-reference the `rootUrl`s with corresponding app folders in vets-website
- use the CODEOWNERS file in vets-website to identify owning teams and tag them on this PR
- if you can't tag them on this PR due to content-build repo permissions, identify the team's Slack channel (or reach out in a front end channel) to try to find someone who can verify the changes

This is the only URL that Sitewide owns that is affected by these changes: `/resources/search`. I checked that page and all is good 👍🏻 

I spot-checked the review instance at http://1a626e4b812e81cd2752257736a67b90.review.vetsgov-internal/pension/apply-for-veteran-pension-form-21p-527ez/introduction. The h1 does not match the final breadcrumb. Presumably there's some API call that is failing in that env to cause it to get the error page, but the h1s should match I think?

Also, when the apply page does appear correctly, it should have "Veterans Pension" capitalized. See prod screenshot for casing.

**Review instance**
Screenshot 2024-09-30 at 11 17 31 AM

**Prod**
Screenshot 2024-09-30 at 11 18 05 AM

CC @jilladams @FranECross

**Comment by jilladams** [comment]
@Andrew565 given recent unintended consequences of big changes in prod, could you help spell out if you've identified reviewers from the owners of all the impacted products here? 

cc @micahchiang

**Comment by randimays** [comment]
CC @aklausmeier

**Comment by Andrew565** [comment]
Need visual confirmation and/or code review approvals from the majority of the following CODEOWNERS for the accompanying URLs, please and thanks! Leave a comment if you find a bug, check the box if the breadcrumbs for your pages look good!

@department-of-veterans-affairs/1010-health-apps-frontend

- [ ] http://52c18a7de0eadb38e08248a07d3f5c86.review.vetsgov-internal/family-and-caregiver-benefits/health-and-disability/comprehensive-assistance-for-family-caregivers/apply-form-10-10cg
- [ ] http://52c18a7de0eadb38e08248a07d3f5c86.review.vetsgov-internal/health-care/apply-for-health-care-form-10-10ez
- [ ] http://52c18a7de0eadb38e08248a07d3f5c86.review.vetsgov-internal/my-health/update-benefits-information-form-10-10ezr

@department-of-veterans-affairs/bah-mbs-selfserv

- [ ] http://52c18a7de0eadb38e08248a07d3f5c86.review.vetsgov-internal/burials-and-memorials/pre-need/form-10007-apply-for-eligibility

@department-of-veterans-affairs/benefits-management-tools-fe

- [ ] http://52c18a7de0eadb38e08248a07d3f5c86.review.vetsgov-internal/disability/view-disability-rating/rating
- [ ] http://52c18a7de0eadb38e08248a07d3f5c86.review.vetsgov-internal/records/download-va-letters/letters
- [ ] http://52c18a7de0eadb38e08248a07d3f5c86.review.vetsgov-internal/records/get-veteran-id-cards/apply

@department-of-veterans-affairs/benefits-non-disability

- [ ] http://52c18a7de0eadb38e08248a07d3f5c86.review.vetsgov-internal/burials-memorials/veterans-burial-allowance/apply-for-allowance-form-21p-530ez
- [ ] http://52c18a7de0eadb38e08248a07d3f5c86.review.vetsgov-internal/careers-employment/education-and-career-counseling/apply-career-guidance-form-25-8832
- [ ] http://52c18a7de0eadb38e08248a07d3f5c86.review.vetsgov-internal/careers-employment/vocational-rehabilitation/apply-vre-form-28-1900
- [ ] http://52c18a7de0eadb38e08248a07d3f5c86.review.vetsgov-internal/housing-assistance/home-loans/check-coe-status/your-coe
- [ ] http://52c18a7de0eadb38e08248a07d3f5c86.review.vetsgov-internal/housing-assistance/home-loans/request-coe-form-26-1880

@department-of-veterans-affairs/disability-experience

- [ ] http://52c18a7de0eadb38e08248a07d3f5c86.review.vetsgov-internal/va-payment-history/payments
- [ ] http://52c18a7de0eadb38e08248a07d3f5c86.review.vetsgov-internal/view-change-dependents/add-remove-form-21-686c
- [ ] http://52c18a7de0eadb38e08248a07d3f5c86.review.vetsgov-internal/view-change-dependents/add-remove-form-21-686c-v2

@department-of-veterans-affairs/govcio-vfep-codereviewers

- [ ] http://52c18a7de0eadb38e08248a07d3f5c86.review.vetsgov-internal/education/about-gi-bill-benefits/how-to-use-benefits/vettec-high-tech-program/apply-for-vettec-form-22-0994
- [ ] http://52c18a7de0eadb38e08248a07d3f5c86.review.vetsgov-internal/education/apply-for-education-benefits/application/1990
- [ ] http://52c18a7de0eadb38e08248a07d3f5c86.review.vetsgov-internal/education/apply-for-education-benefits/application/1995
- [ ] http://52c18a7de0eadb38e08248a07d3f5c86.review.vetsgov-internal/education/apply-for-education-benefits/application/5495
- [ ] http://52c18a7de0eadb38e08248a07d3f5c86.review.vetsgov-internal/education/gi-bill/post-9-11/ch-33-benefit/status
- [ ] http://52c18a7de0eadb38e08248a07d3f5c86.review.vetsgov-internal/education/opt-out-information-sharing/opt-out-form-0993
- [ ] http://52c18a7de0eadb38e08248a07d3f5c86.review.vetsgov-internal/education/other-va-education-benefits/stem-scholarship/apply-for-scholarship-form-22-10203
- [ ] http://52c18a7de0eadb38e08248a07d3f5c86.review.vetsgov-internal/education/submit-school-feedback

@department-of-veterans-affairs/pensions

- [ ] http://52c18a7de0eadb38e08248a07d3f5c86.review.vetsgov-internal/income-and-asset-statement-form-21p-0969
- [ ] http://52c18a7de0eadb38e08248a07d3f5c86.review.vetsgov-internal/pension/application/527EZ
- [ ] http://52c18a7de0eadb38e08248a07d3f5c86.review.vetsgov-internal/pension/apply-for-veteran-pension-form-21p-527ez

@department-of-veterans-affairs/platform-va-product-forms

- [ ] http://52c18a7de0eadb38e08248a07d3f5c86.review.vetsgov-internal/burials-memorials/memorial-items/presidential-memorial-certificates/request-certificate-form-40-0247
- [ ] http://52c18a7de0eadb38e08248a07d3f5c86.review.vetsgov-internal/housing-assistance/disability-housing-grants/apply-for-grant-form-26-4555
- [ ] http://52c18a7de0eadb38e08248a07d3f5c86.review.vetsgov-internal/mock-form
- [ ] http://52c18a7de0eadb38e08248a07d3f5c86.review.vetsgov-internal/records/request-personal-records-form-20-10206
- [ ] http://52c18a7de0eadb38e08248a07d3f5c86.review.vetsgov-internal/supporting-forms-for-claims/alternate-signer-form-21-0972
- [ ] http://52c18a7de0eadb38e08248a07d3f5c86.review.vetsgov-internal/supporting-forms-for-claims/intent-to-file-form-21-0966
- [ ] http://52c18a7de0eadb38e08248a07d3f5c86.review.vetsgov-internal/supporting-forms-for-claims/lay-witness-statement-form-21-10210
- [ ] http://52c18a7de0eadb38e08248a07d3f5c86.review.vetsgov-internal/supporting-forms-for-claims/release-information-to-va-form-21-4142
- [ ] http://52c18a7de0eadb38e08248a07d3f5c86.review.vetsgov-internal/supporting-forms-for-claims/request-priority-processing-form-20-10207
- [ ] http://52c18a7de0eadb38e08248a07d3f5c86.review.vetsgov-internal/supporting-forms-for-claims/substitute-claimant-form-21P-0847
- [ ] http://52c18a7de0eadb38e08248a07d3f5c86.review.vetsgov-internal/supporting-forms-for-claims/third-party-authorization-form-21-0845

@department-of-veterans-affairs/va-cto-health-products

- [ ] http://52c18a7de0eadb38e08248a07d3f5c86.review.vetsgov-internal/coronavirus-research/volunteer
- [ ] http://52c18a7de0eadb38e08248a07d3f5c86.review.vetsgov-internal/coronavirus-research/volunteer/update

@department-of-veterans-affairs/vfs-public-websites-frontend

- [ ] http://52c18a7de0eadb38e08248a07d3f5c86.review.vetsgov-internal/resources/search

@department-of-veterans-affairs/vsa-authd-exp-frontend

- [ ] http://52c18a7de0eadb38e08248a07d3f5c86.review.vetsgov-internal/view-change-dependents/view

@department-of-veterans-affairs/vsa-debt-frontend

- [ ] http://52c18a7de0eadb38e08248a07d3f5c86.review.vetsgov-internal/manage-va-debt/request-debt-help-form-5655

**Review by randimays — APPROVED** [review]
Approved for `/resources/search` / Public Websites

**Review by acrollet — APPROVED** [review]
coronavirus research changes approved (the app is deprecated and slated to be removed)

**Comment by longmd** [comment]
@Andrew565 , after reviewing the 10-10 apps, the links go to their appropriate pages, as expected. I did notice an issue with word casing. If you reference the current and updated breadcrumbs, notice that `VA` is now lowercase. I assume this may be something within the web component itself that is forcing lowercase on all but the first letter of the title?

| Current | Updated |
| -------- | -------- |
| Screenshot 2024-10-04 at 15 14 19 | Screenshot 2024-10-04 at 15 12 50 |

**Comment by Andrew565** [comment]
> If you reference the current and updated breadcrumbs, notice that `VA` is now lowercase. I assume this may be something within the web component itself that is forcing lowercase on all but the first letter of the title?

@longmd It's actually part of the Liquid Filter that I set up, it's supposed to lowercase any non-custom breadcrumbs, which is the behavior that was part of the old breadcrumbs.html setup. I'll see if there's a good way to fix that for the VA acronym specifically.

**Comment by DLarson-Oddball** [comment]
Hey @Andrew565! I reviewed this PR on behalf of @department-of-veterans-affairs/benefits-non-disability, and noticed the casing issue also applies to "Veteran". Can you extend your capitalization fix to this word as well?

**Comment by Andrew565** [comment]
Yes

**Comment by GovCIOLiz** [comment]
@Andrew565 I reviewed the @department-of-veterans-affairs/govcio-vfep-codereviewers instances and `STEM, Edith Nourse Rogers, GI Bill, and Vet Tec` have lost their capitalization

**Comment by Andrew565** [comment]
Capitalization fixed, no longer lowercases the entire title, just uppercases the first word as needed. (I incorrectly read how the 'capitalize' filter worked when I was implementing it the first time.)

**Comment by Andrew565** [comment]
Review instance links updated.

**Comment by Andrew565** [comment]
Review instance links updated again.

**Review by longmd — APPROVED** [review]
Good to go for the 10-10 team apps. 🚀

**Comment by randimays** [comment]
@Andrew565 Were you able to get confirmation from all the affected teams/products that the breadcrumbs worked as expected? Noticed in [this comment](https://github.com/department-of-veterans-affairs/content-build/pull/2254#issuecomment-2393885220) that the checklist wasn't complete, just wanted to make sure.

**Comment by Andrew565** [comment]
I got enough to be reasonably sure that it was working as expected.

**Pull request merged**
