### PR TITLE
My Education Benefits: Change root Url to approved path

### PR DESCRIPTION
**Pull request by cesaresantiago**
## Description
- We've received approval for My Education Benefits app's root url. This change makes it /education/apply-for-benefits-form-22-1990

When this change makes it in, we'll make the corresponding manifest.json change in vets-website on PR https://github.com/department-of-veterans-affairs/vets-website/pull/18889

## Acceptance criteria
- [ ]

## Definition of done
- [ ] Events are logged appropriately
- [ ] Documentation has been updated, if applicable
- [ ] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)
- [ ] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

### CODE REVIEW

**Comment by theodur** [comment]
@cesaresantiago Do you have a PR to update the `manifest.json` file as well in the `vets-website` repo?

**Comment by cesaresantiago** [comment]
> @cesaresantiago Do you have a PR to update the `manifest.json` file as well in the `vets-website` repo?

Yes, we do: https://github.com/department-of-veterans-affairs/vets-website/pull/18889

**Comment by cesaresantiago** [comment]
Investigating PR build faillure.

**Comment by theodur** [comment]
CI is failing because the updated `entryName` doesn't exist in the dev assets bucket since the vets-website PR hasn't been merged in yet.

**Review by theodur — APPROVED** [review]

**Pull request merged**
