### PR TITLE
Build prototype for new focus styles

### PR DESCRIPTION
**Pull request by bkjohnson**
## Description
Closes https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1058

Related PRs:

- https://github.com/department-of-veterans-affairs/veteran-facing-services-tools/pull/857
- https://github.com/department-of-veterans-affairs/component-library/pull/433

This adds pre-release packages of `formation` and `component-library` to the Covid-19 healthcare page in order to test the new double box-shadow focus styles. They are designed to be easily removed.

The prototype will live [here on staging](https://staging.va.gov/health-care/covid-19-vaccine/).

## Testing done

Local build :eyes: 

### Header

Screenshot of the header on a localhost build, with the new focus style on the "Contact us" button

### On this page

Screenshot of the "On this page" component on a localhost build, with one of the links having the new focus style.

### Pages not part of the prototype

Screenshot of a page that isn't the Covid-19 page. An item in the header is focused, and it retains the original focus styling.

## Acceptance criteria
- [ ]

## Definition of done
- [ ] Events are logged appropriately
- [ ] Documentation has been updated, if applicable
- [ ] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)
- [ ] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

### CODE REVIEW

**Review by bkjohnson — COMMENTED** [review]
Also, since I'm basically doing the same check in two places,  I tried something like this:

```liquid
{% assign focusStylePrototype = entityId == 11463 and buildtype != "vagovprod" %}
```

And then using that variable inside the if statements, but this didn't work as expected.

**Comment by bkjohnson** [comment]
cc @GnatalieH. This autocomplete didn't work for me, and your name wasn't available to me in the assignees or reviewers fields.

**Comment by GnatalieH** [comment]
> cc @GnatalieH. This autocomplete didn't work for me, and your name wasn't available to me in the assignees or reviewers fields.

@bkjohnson question: why is the current header under the Pages not part of this prototype section? I'm wondering if I can review this prototype to run through the tasks in the user test, too. Thanks.

**Comment by bkjohnson** [comment]
I added that screenshot of the `/health-care/refill-track-prescriptions` page to show that the new focus styles aren't applied to pages that aren't the Covid-19 page.

**Review by andresriveratoro — APPROVED** [review]

**Comment by bkjohnson** [comment]
@department-of-veterans-affairs/vsa-public-websites-frontend can I get a review on this?

**Comment by bkjohnson** [comment]
@department-of-veterans-affairs/vsa-public-websites-frontend @department-of-veterans-affairs/vsa-caregiver-frontend @department-of-veterans-affairs/vsa-facilities-backend 

Would someone from one of these teams review this as a codeowner?

**Review by allisonlu — APPROVED** [review]

**Pull request merged**
