### PR TITLE
VEBT-424 React SCO page to prod

### PR DESCRIPTION
**Pull request by GovCIOLiz**
## Summary

The VEBT team has been working to update the current SCO page to a react app. This PR flips `vagovprod` to true.

This PR will be merged after [this content-build PR](https://github.com/department-of-veterans-affairs/content-build/pull/2245/files), [this revproxy PR](https://github.com/department-of-veterans-affairs/vsp-platform-revproxy/pull/597), and [this vets-website PR](https://github.com/department-of-veterans-affairs/vets-website/pull/31503) that update the route to match the current production route for the SCO page.

## Related issue(s)

[VEBT-424](https://jira.devops.va.gov/browse/VEBT-424)

Acceptance Criteria:
Registry.json file in the content build repo, value of FALSE is changed to TRUE for vagovprod

## Testing done

- _Describe what the old behavior was prior to the change_
- _Describe the steps required to verify your changes are working as expected_
- _Describe the tests completed and the results_
- _Exclusively stating 'Specs and automated tests passing' is NOT acceptable as appropriate testing
- _Optionally, provide a link to your [test plan](https://depo-platform-documentation.scrollhelp.site/developer-docs/create-a-test-plan-in-testrail) and [test execution records](https://depo-platform-documentation.scrollhelp.site/developer-docs/execute-tests-in-testrail)_

## Screenshots

_Note: This field is mandatory for UI changes (non-component work should NOT have screenshots)._

|         | Before | After |
| ------- | ------ | ----- |
| Mobile  |        |       |
| Desktop |        |       |

## What areas of the site does it impact?

*(Describe what parts of the site are impacted **if** code touched other areas)*

### Quality Assurance & Testing

- [ ] I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [ ] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs
- [ ] Linting warnings have been addressed
- [ ] Documentation has been updated ([link to documentation](#) \*if necessary)
- [ ] Screenshot of the developed feature is added
- [ ] [Accessibility testing](https://depo-platform-documentation.scrollhelp.site/developer-docs/wcag-2-1-success-criteria-and-foundational-testing) has been performed

### Error Handling

- [ ] Browser console contains no warnings or errors.
- [ ] Events are being sent to the appropriate logging solution
- [ ] Feature/bug has a monitor built into Datadog or Grafana (if applicable)

### Authentication

- [ ] Did you login to a local build and verify all authenticated routes work as expected with a test user

## Requested Feedback

(OPTIONAL) _What should the reviewers know in addition to the above. Is there anything specific you wish the reviewer to assist with. Do you have any concerns with this PR, why?_

### CODE REVIEW

**Comment by randimays** [comment]
Should this include removal of this template (and the code that references it)? https://github.com/department-of-veterans-affairs/content-build/blob/main/src/site/includes/education-sco.html

**Comment by jsimonVA** [comment]
> Should this include removal of this template (and the code that references it)? https://github.com/department-of-veterans-affairs/content-build/blob/main/src/site/includes/education-sco.html

We have no plans to include removal of anything with this PR. 
The intent for this PR is solely to "Go Live" with the new SCO React page. 
Once this PR is pushed and the new SCO page is live, we will contact the Content-Team on steps to remove the old SCO artifacts.

**Review by jsimonVA — APPROVED** [review]
LGTM, this is to go live with the new React SCO page.

**Review by rmessina1010 — APPROVED** [review]
LGTM

**Pull request merged**
