### PR TITLE
VACMS-7163: Remove "va-lovell-federal-health-care" menu from "facilitySidebar.nav.graphql.js" VISN 12 section

### PR DESCRIPTION
**Pull request by netboss**
- Removed "va-lovell-federal-health-care" menu from "facilitySidebar.nav.graphql.js" VISN 12 section.

## Description

closes #7163

## Testing done

All tests passes

## Acceptance criteria
- [ ]

## Definition of done
- [ ] Events are logged appropriately
- [ ] Documentation has been updated, if applicable
- [ ] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)
- [ ] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

### CODE REVIEW

**Comment by netboss** [comment]
@swirtSJW 
Changed this to draft to wait for #839. Or can I leave it as open?

**Review by swirtSJW — APPROVED** [review]
@netboss you should be able to take this out of draft now.  Now that your CMS pr went to prod, we can get this merged.

**Comment by swirtSJW** [comment]
Content is now ready for this.  Tests should pass on it now.

**Comment by netboss** [comment]
@swirtSJW 
Just rebased and re-pushed. All jobs/tests passed.

**Comment by swirtSJW** [comment]
@srsuddath any change you can take a look at this?

**Review by srsuddath — APPROVED** [review]

**Pull request merged**
