### PR TITLE
VACMS-16952 VAMC System pages web components

### PR DESCRIPTION
**Pull request by randimays**
## Summary
Add v1 and v3 web components to VAMC system pages where possible. Converts the "See all (locations/stories/events)" buttons to active links.

## Related issue(s)
- https://github.com/department-of-veterans-affairs/va.gov-cms/issues/16952
- https://github.com/department-of-veterans-affairs/va.gov-cms/issues/15598

## Testing done
Tested locally on `/boston-health-care` and `/minneapolis-health-care`.

## Screenshots

<details><summary>See all (locations/stories/events) to active link</summary>

### Locations
Screenshot 2024-05-17 at 1 47 07 PM
Screenshot 2024-05-17 at 1 47 03 PM

### Stories
Screenshot 2024-05-17 at 2 08 34 PM
Screenshot 2024-05-22 at 10 15 12 AM

### Events
Screenshot 2024-05-22 at 10 14 49 AM
Screenshot 2024-05-22 at 10 15 20 AM
</details>

<details><summary>"Manage your health online" icons</summary>

### Desktop
Screenshot 2024-05-17 at 1 46 22 PM

### Mobile
Screenshot 2024-05-22 at 10 25 47 AM

### DOM
Screenshot 2024-05-17 at 1 46 51 PM

</details>

<details><summary>Full width banners</summary>

### Desktop
Screenshot 2024-05-22 at 10 29 59 AM

### Mobile
Screenshot 2024-05-22 at 10 30 05 AM

### DOM
Screenshot 2024-05-22 at 10 24 32 AM

</details>

<details><summary>Back to top</summary>

### Desktop
Screenshot 2024-05-22 at 10 32 40 AM

### Mobile
Screenshot 2024-05-22 at 10 32 32 AM

### DOM
Screenshot 2024-05-22 at 10 32 48 AM

</details>

<details><summary>Related links</summary>

### Desktop
Screenshot 2024-05-22 at 10 36 10 AM

### Mobile
Screenshot 2024-05-22 at 10 36 42 AM

### DOM
Screenshot 2024-05-22 at 10 36 34 AM

</details>

### CODE REVIEW

**Review by eselkin — APPROVED** [review]
LGTM

**Comment by laflannery** [comment]
@randimays My only question is if the Stories link can be a va-link component - Unless this will get changed in [the separate stories ticket](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17067) (because Events has changed so perhaps that's how that happened already)?

**Comment by randimays** [comment]
@laflannery Is this the Stories link you're referring to? If so, that one is a va-link on my end.

Screenshot 2024-05-23 at 10 10 07 AM

Screenshot 2024-05-23 at 10 10 00 AM

**Comment by laflannery** [comment]
Yep, that's it - I just didn't see a screenshot for it - sorry about that, Approved!

**Comment by randimays** [comment]
@laflannery My apologies for missing that screenshot! Thank you :)

**Pull request merged**
